// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MastersColumns holds the columns for the "masters" table.
	MastersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "version", Type: field.TypeString},
		{Name: "supersedes_version", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "title_id", Type: field.TypeString},
	}
	// MastersTable holds the schema information for the "masters" table.
	MastersTable = &schema.Table{
		Name:       "masters",
		Columns:    MastersColumns,
		PrimaryKey: []*schema.Column{MastersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "masters_titles_masters",
				Columns:    []*schema.Column{MastersColumns[4]},
				RefColumns: []*schema.Column{TitlesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// MediaPackagesColumns holds the columns for the "media_packages" table.
	MediaPackagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "component", Type: field.TypeEnum, Enums: []string{"VIDEO", "AUDIO", "SUBTITLE", "METADATA"}},
		{Name: "language", Type: field.TypeString},
		{Name: "version", Type: field.TypeString},
		{Name: "derived_from_master_version", Type: field.TypeString},
		{Name: "redelivery_count", Type: field.TypeInt, Default: 0},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PENDING", "VALID", "INVALIDATED", "RE_QC_PENDING"}, Default: "PENDING"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "title_id", Type: field.TypeString},
		{Name: "vendor_id", Type: field.TypeString},
	}
	// MediaPackagesTable holds the schema information for the "media_packages" table.
	MediaPackagesTable = &schema.Table{
		Name:       "media_packages",
		Columns:    MediaPackagesColumns,
		PrimaryKey: []*schema.Column{MediaPackagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "media_packages_titles_packages",
				Columns:    []*schema.Column{MediaPackagesColumns[9]},
				RefColumns: []*schema.Column{TitlesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "media_packages_vendors_packages",
				Columns:    []*schema.Column{MediaPackagesColumns[10]},
				RefColumns: []*schema.Column{VendorsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TitlesColumns holds the columns for the "titles" table.
	TitlesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"FEATURE", "SERIES", "SPECIAL"}, Default: "FEATURE"},
		{Name: "premiere_date", Type: field.TypeTime},
		{Name: "territories", Type: field.TypeInt, Default: 1},
		{Name: "current_master_version", Type: field.TypeString},
		{Name: "overall_status", Type: field.TypeEnum, Enums: []string{"ON_TRACK", "AT_RISK", "HOLD", "PROCESSING", "SHIPPED"}, Default: "PROCESSING"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TitlesTable holds the schema information for the "titles" table.
	TitlesTable = &schema.Table{
		Name:       "titles",
		Columns:    TitlesColumns,
		PrimaryKey: []*schema.Column{TitlesColumns[0]},
	}
	// VendorsColumns holds the columns for the "vendors" table.
	VendorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "specialty", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// VendorsTable holds the schema information for the "vendors" table.
	VendorsTable = &schema.Table{
		Name:       "vendors",
		Columns:    VendorsColumns,
		PrimaryKey: []*schema.Column{VendorsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MastersTable,
		MediaPackagesTable,
		TitlesTable,
		VendorsTable,
	}
)

func init() {
	MastersTable.ForeignKeys[0].RefTable = TitlesTable
	MediaPackagesTable.ForeignKeys[0].RefTable = TitlesTable
	MediaPackagesTable.ForeignKeys[1].RefTable = VendorsTable
}
