// Code generated by ent, DO NOT EDIT.

package master

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the master type in the database.
	Label = "master"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitleID holds the string denoting the title_id field in the database.
	FieldTitleID = "title_id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldSupersedesVersion holds the string denoting the supersedes_version field in the database.
	FieldSupersedesVersion = "supersedes_version"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeTitle holds the string denoting the title edge name in mutations.
	EdgeTitle = "title"
	// Table holds the table name of the master in the database.
	Table = "masters"
	// TitleTable is the table that holds the title relation/edge.
	TitleTable = "masters"
	// TitleInverseTable is the table name for the Title entity.
	// It exists in this package in order to avoid circular dependency with the "title" package.
	TitleInverseTable = "titles"
	// TitleColumn is the table column denoting the title relation/edge.
	TitleColumn = "title_id"
)

// Columns holds all SQL columns for master fields.
var Columns = []string{
	FieldID,
	FieldTitleID,
	FieldVersion,
	FieldSupersedesVersion,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleIDValidator is a validator for the "title_id" field. It is called by the builders before save.
	TitleIDValidator func(string) error
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Master queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitleID orders the results by the title_id field.
func ByTitleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitleID, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// BySupersedesVersion orders the results by the supersedes_version field.
func BySupersedesVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupersedesVersion, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByTitleField orders the results by title field.
func ByTitleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTitleStep(), sql.OrderByField(field, opts...))
	}
}
func newTitleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TitleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TitleTable, TitleColumn),
	)
}
