// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DeliveriesColumns holds the columns for the "deliveries" table.
	DeliveriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "country", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PENDING", "READY_TO_SHIP", "HOLD", "SHIPPED"}, Default: "PENDING"},
		{Name: "target_date", Type: field.TypeTime},
		{Name: "title_id", Type: field.TypeString},
	}
	// DeliveriesTable holds the schema information for the "deliveries" table.
	DeliveriesTable = &schema.Table{
		Name:       "deliveries",
		Columns:    DeliveriesColumns,
		PrimaryKey: []*schema.Column{DeliveriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "deliveries_titles_deliveries",
				Columns:    []*schema.Column{DeliveriesColumns[7]},
				RefColumns: []*schema.Column{TitlesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "delivery_title_id",
				Unique:  false,
				Columns: []*schema.Column{DeliveriesColumns[7]},
			},
			{
				Name:    "delivery_status",
				Unique:  false,
				Columns: []*schema.Column{DeliveriesColumns[5]},
			},
			{
				Name:    "delivery_country",
				Unique:  false,
				Columns: []*schema.Column{DeliveriesColumns[4]},
			},
		},
	}
	// DependenciesColumns holds the columns for the "dependencies" table.
	DependenciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "dependency_type", Type: field.TypeEnum, Enums: []string{"AUDIO_SYNC", "SUBTITLE_ALIGNMENT", "MASTER_DERIVATION"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "parent_id", Type: field.TypeString},
		{Name: "child_id", Type: field.TypeString},
	}
	// DependenciesTable holds the schema information for the "dependencies" table.
	DependenciesTable = &schema.Table{
		Name:       "dependencies",
		Columns:    DependenciesColumns,
		PrimaryKey: []*schema.Column{DependenciesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "dependencies_media_packages_dependent_children",
				Columns:    []*schema.Column{DependenciesColumns[3]},
				RefColumns: []*schema.Column{MediaPackagesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "dependencies_media_packages_parent_dependencies",
				Columns:    []*schema.Column{DependenciesColumns[4]},
				RefColumns: []*schema.Column{MediaPackagesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "dependency_parent_id_child_id",
				Unique:  true,
				Columns: []*schema.Column{DependenciesColumns[3], DependenciesColumns[4]},
			},
			{
				Name:    "dependency_parent_id",
				Unique:  false,
				Columns: []*schema.Column{DependenciesColumns[3]},
			},
			{
				Name:    "dependency_child_id",
				Unique:  false,
				Columns: []*schema.Column{DependenciesColumns[4]},
			},
		},
	}
	// MastersColumns holds the columns for the "masters" table.
	MastersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "version", Type: field.TypeString},
		{Name: "supersedes_version", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "title_id", Type: field.TypeString},
	}
	// MastersTable holds the schema information for the "masters" table.
	MastersTable = &schema.Table{
		Name:       "masters",
		Columns:    MastersColumns,
		PrimaryKey: []*schema.Column{MastersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "masters_titles_masters",
				Columns:    []*schema.Column{MastersColumns[4]},
				RefColumns: []*schema.Column{TitlesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "master_title_id",
				Unique:  false,
				Columns: []*schema.Column{MastersColumns[4]},
			},
			{
				Name:    "master_title_id_version",
				Unique:  true,
				Columns: []*schema.Column{MastersColumns[4], MastersColumns[1]},
			},
		},
	}
	// MediaPackagesColumns holds the columns for the "media_packages" table.
	MediaPackagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "component", Type: field.TypeEnum, Enums: []string{"VIDEO", "AUDIO", "SUBTITLE", "METADATA"}},
		{Name: "language", Type: field.TypeString},
		{Name: "version", Type: field.TypeString},
		{Name: "derived_from_master_version", Type: field.TypeString},
		{Name: "redelivery_count", Type: field.TypeInt, Default: 0},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PENDING", "VALID", "INVALIDATED", "RE_QC_PENDING"}, Default: "PENDING"},
		{Name: "market", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "title_id", Type: field.TypeString},
		{Name: "vendor_id", Type: field.TypeString},
	}
	// MediaPackagesTable holds the schema information for the "media_packages" table.
	MediaPackagesTable = &schema.Table{
		Name:       "media_packages",
		Columns:    MediaPackagesColumns,
		PrimaryKey: []*schema.Column{MediaPackagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "media_packages_titles_packages",
				Columns:    []*schema.Column{MediaPackagesColumns[11]},
				RefColumns: []*schema.Column{TitlesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "media_packages_vendors_packages",
				Columns:    []*schema.Column{MediaPackagesColumns[12]},
				RefColumns: []*schema.Column{VendorsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "mediapackage_title_id",
				Unique:  false,
				Columns: []*schema.Column{MediaPackagesColumns[11]},
			},
			{
				Name:    "mediapackage_vendor_id",
				Unique:  false,
				Columns: []*schema.Column{MediaPackagesColumns[12]},
			},
			{
				Name:    "mediapackage_status",
				Unique:  false,
				Columns: []*schema.Column{MediaPackagesColumns[9]},
			},
			{
				Name:    "mediapackage_component",
				Unique:  false,
				Columns: []*schema.Column{MediaPackagesColumns[4]},
			},
			{
				Name:    "mediapackage_market",
				Unique:  false,
				Columns: []*schema.Column{MediaPackagesColumns[10]},
			},
		},
	}
	// RunsColumns holds the columns for the "runs" table.
	RunsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "title_slug", Type: field.TypeString, Default: "GLOBAL"},
		{Name: "trigger", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PENDING", "RUNNING", "COMPLETED", "FAILED", "ESCALATED"}, Default: "RUNNING"},
		{Name: "started_at", Type: field.TypeTime},
		{Name: "ended_at", Type: field.TypeTime, Nullable: true},
	}
	// RunsTable holds the schema information for the "runs" table.
	RunsTable = &schema.Table{
		Name:       "runs",
		Columns:    RunsColumns,
		PrimaryKey: []*schema.Column{RunsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "run_status",
				Unique:  false,
				Columns: []*schema.Column{RunsColumns[6]},
			},
			{
				Name:    "run_trigger",
				Unique:  false,
				Columns: []*schema.Column{RunsColumns[5]},
			},
			{
				Name:    "run_title_slug",
				Unique:  false,
				Columns: []*schema.Column{RunsColumns[4]},
			},
		},
	}
	// StepsColumns holds the columns for the "steps" table.
	StepsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PENDING", "RUNNING", "COMPLETED", "FAILED", "SKIPPED"}, Default: "RUNNING"},
		{Name: "started_at", Type: field.TypeTime},
		{Name: "ended_at", Type: field.TypeTime, Nullable: true},
		{Name: "run_id", Type: field.TypeString},
	}
	// StepsTable holds the schema information for the "steps" table.
	StepsTable = &schema.Table{
		Name:       "steps",
		Columns:    StepsColumns,
		PrimaryKey: []*schema.Column{StepsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "steps_runs_steps",
				Columns:    []*schema.Column{StepsColumns[8]},
				RefColumns: []*schema.Column{RunsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "step_run_id",
				Unique:  false,
				Columns: []*schema.Column{StepsColumns[8]},
			},
			{
				Name:    "step_status",
				Unique:  false,
				Columns: []*schema.Column{StepsColumns[5]},
			},
			{
				Name:    "step_name",
				Unique:  false,
				Columns: []*schema.Column{StepsColumns[4]},
			},
		},
	}
	// TitlesColumns holds the columns for the "titles" table.
	TitlesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"FEATURE", "SERIES", "SPECIAL"}, Default: "FEATURE"},
		{Name: "premiere_date", Type: field.TypeTime},
		{Name: "territories", Type: field.TypeInt, Default: 1},
		{Name: "current_master_version", Type: field.TypeString, Default: ""},
		{Name: "overall_status", Type: field.TypeEnum, Enums: []string{"ON_TRACK", "AT_RISK", "HOLD", "PROCESSING", "SHIPPED"}, Default: "PROCESSING"},
	}
	// TitlesTable holds the schema information for the "titles" table.
	TitlesTable = &schema.Table{
		Name:       "titles",
		Columns:    TitlesColumns,
		PrimaryKey: []*schema.Column{TitlesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "title_overall_status",
				Unique:  false,
				Columns: []*schema.Column{TitlesColumns[10]},
			},
			{
				Name:    "title_type",
				Unique:  false,
				Columns: []*schema.Column{TitlesColumns[6]},
			},
		},
	}
	// UploadsColumns holds the columns for the "uploads" table.
	UploadsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "filename", Type: field.TypeString},
		{Name: "mime_type", Type: field.TypeString},
		{Name: "data", Type: field.TypeBytes},
		{Name: "size_bytes", Type: field.TypeInt64},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UploadsTable holds the schema information for the "uploads" table.
	UploadsTable = &schema.Table{
		Name:       "uploads",
		Columns:    UploadsColumns,
		PrimaryKey: []*schema.Column{UploadsColumns[0]},
	}
	// VendorsColumns holds the columns for the "vendors" table.
	VendorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "specialty", Type: field.TypeString},
		{Name: "hourly_rate_usd", Type: field.TypeFloat64, Default: 0},
		{Name: "turnaround_hours", Type: field.TypeInt, Default: 24},
	}
	// VendorsTable holds the schema information for the "vendors" table.
	VendorsTable = &schema.Table{
		Name:       "vendors",
		Columns:    VendorsColumns,
		PrimaryKey: []*schema.Column{VendorsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "vendor_specialty",
				Unique:  false,
				Columns: []*schema.Column{VendorsColumns[5]},
			},
		},
	}
	// WfResultsColumns holds the columns for the "wf_results" table.
	WfResultsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "judge", Type: field.TypeString},
		{Name: "outcome", Type: field.TypeString},
		{Name: "rationale", Type: field.TypeString, Default: ""},
		{Name: "attempt", Type: field.TypeInt, Default: 1},
		{Name: "run_id", Type: field.TypeString},
		{Name: "step_id", Type: field.TypeString, Nullable: true},
	}
	// WfResultsTable holds the schema information for the "wf_results" table.
	WfResultsTable = &schema.Table{
		Name:       "wf_results",
		Columns:    WfResultsColumns,
		PrimaryKey: []*schema.Column{WfResultsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "wf_results_runs_results",
				Columns:    []*schema.Column{WfResultsColumns[8]},
				RefColumns: []*schema.Column{RunsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "wf_results_steps_results",
				Columns:    []*schema.Column{WfResultsColumns[9]},
				RefColumns: []*schema.Column{StepsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "wfresult_run_id",
				Unique:  false,
				Columns: []*schema.Column{WfResultsColumns[8]},
			},
			{
				Name:    "wfresult_step_id",
				Unique:  false,
				Columns: []*schema.Column{WfResultsColumns[9]},
			},
			{
				Name:    "wfresult_judge",
				Unique:  false,
				Columns: []*schema.Column{WfResultsColumns[4]},
			},
			{
				Name:    "wfresult_outcome",
				Unique:  false,
				Columns: []*schema.Column{WfResultsColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DeliveriesTable,
		DependenciesTable,
		MastersTable,
		MediaPackagesTable,
		RunsTable,
		StepsTable,
		TitlesTable,
		UploadsTable,
		VendorsTable,
		WfResultsTable,
	}
)

func init() {
	DeliveriesTable.ForeignKeys[0].RefTable = TitlesTable
	DependenciesTable.ForeignKeys[0].RefTable = MediaPackagesTable
	DependenciesTable.ForeignKeys[1].RefTable = MediaPackagesTable
	MastersTable.ForeignKeys[0].RefTable = TitlesTable
	MediaPackagesTable.ForeignKeys[0].RefTable = TitlesTable
	MediaPackagesTable.ForeignKeys[1].RefTable = VendorsTable
	StepsTable.ForeignKeys[0].RefTable = RunsTable
	WfResultsTable.ForeignKeys[0].RefTable = RunsTable
	WfResultsTable.ForeignKeys[1].RefTable = StepsTable
}
