// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/elliot14A/fincher/internal/turso/ent/delivery"
	"github.com/elliot14A/fincher/internal/turso/ent/title"
)

// DeliveryCreate is the builder for creating a Delivery entity.
type DeliveryCreate struct {
	config
	mutation *DeliveryMutation
	hooks    []Hook
}

// SetMetadata sets the "metadata" field.
func (_c *DeliveryCreate) SetMetadata(v map[string]interface{}) *DeliveryCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeliveryCreate) SetCreatedAt(v time.Time) *DeliveryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeliveryCreate) SetNillableCreatedAt(v *time.Time) *DeliveryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DeliveryCreate) SetUpdatedAt(v time.Time) *DeliveryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DeliveryCreate) SetNillableUpdatedAt(v *time.Time) *DeliveryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTitleID sets the "title_id" field.
func (_c *DeliveryCreate) SetTitleID(v string) *DeliveryCreate {
	_c.mutation.SetTitleID(v)
	return _c
}

// SetCountry sets the "country" field.
func (_c *DeliveryCreate) SetCountry(v string) *DeliveryCreate {
	_c.mutation.SetCountry(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *DeliveryCreate) SetStatus(v delivery.Status) *DeliveryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DeliveryCreate) SetNillableStatus(v *delivery.Status) *DeliveryCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTargetDate sets the "target_date" field.
func (_c *DeliveryCreate) SetTargetDate(v time.Time) *DeliveryCreate {
	_c.mutation.SetTargetDate(v)
	return _c
}

// SetID sets the "id" field.
func (_c *DeliveryCreate) SetID(v string) *DeliveryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTitle sets the "title" edge to the Title entity.
func (_c *DeliveryCreate) SetTitle(v *Title) *DeliveryCreate {
	return _c.SetTitleID(v.ID)
}

// Mutation returns the DeliveryMutation object of the builder.
func (_c *DeliveryCreate) Mutation() *DeliveryMutation {
	return _c.mutation
}

// Save creates the Delivery in the database.
func (_c *DeliveryCreate) Save(ctx context.Context) (*Delivery, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeliveryCreate) SaveX(ctx context.Context) *Delivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeliveryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeliveryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeliveryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := delivery.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := delivery.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := delivery.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeliveryCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Delivery.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Delivery.updated_at"`)}
	}
	if _, ok := _c.mutation.TitleID(); !ok {
		return &ValidationError{Name: "title_id", err: errors.New(`ent: missing required field "Delivery.title_id"`)}
	}
	if v, ok := _c.mutation.TitleID(); ok {
		if err := delivery.TitleIDValidator(v); err != nil {
			return &ValidationError{Name: "title_id", err: fmt.Errorf(`ent: validator failed for field "Delivery.title_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Country(); !ok {
		return &ValidationError{Name: "country", err: errors.New(`ent: missing required field "Delivery.country"`)}
	}
	if v, ok := _c.mutation.Country(); ok {
		if err := delivery.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Delivery.country": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Delivery.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := delivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Delivery.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetDate(); !ok {
		return &ValidationError{Name: "target_date", err: errors.New(`ent: missing required field "Delivery.target_date"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := delivery.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Delivery.id": %w`, err)}
		}
	}
	if len(_c.mutation.TitleIDs()) == 0 {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required edge "Delivery.title"`)}
	}
	return nil
}

func (_c *DeliveryCreate) sqlSave(ctx context.Context) (*Delivery, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Delivery.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeliveryCreate) createSpec() (*Delivery, *sqlgraph.CreateSpec) {
	var (
		_node = &Delivery{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(delivery.Table, sqlgraph.NewFieldSpec(delivery.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(delivery.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(delivery.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(delivery.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Country(); ok {
		_spec.SetField(delivery.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(delivery.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TargetDate(); ok {
		_spec.SetField(delivery.FieldTargetDate, field.TypeTime, value)
		_node.TargetDate = value
	}
	if nodes := _c.mutation.TitleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   delivery.TitleTable,
			Columns: []string{delivery.TitleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(title.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TitleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DeliveryCreateBulk is the builder for creating many Delivery entities in bulk.
type DeliveryCreateBulk struct {
	config
	err      error
	builders []*DeliveryCreate
}

// Save creates the Delivery entities in the database.
func (_c *DeliveryCreateBulk) Save(ctx context.Context) ([]*Delivery, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Delivery, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeliveryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeliveryCreateBulk) SaveX(ctx context.Context) []*Delivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeliveryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeliveryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
