// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/elliot14A/fincher/internal/turso/ent/dependency"
	"github.com/elliot14A/fincher/internal/turso/ent/mediapackage"
	"github.com/elliot14A/fincher/internal/turso/ent/predicate"
)

// DependencyUpdate is the builder for updating Dependency entities.
type DependencyUpdate struct {
	config
	hooks    []Hook
	mutation *DependencyMutation
}

// Where appends a list predicates to the DependencyUpdate builder.
func (_u *DependencyUpdate) Where(ps ...predicate.Dependency) *DependencyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *DependencyUpdate) SetParentID(v string) *DependencyUpdate {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *DependencyUpdate) SetNillableParentID(v *string) *DependencyUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// SetChildID sets the "child_id" field.
func (_u *DependencyUpdate) SetChildID(v string) *DependencyUpdate {
	_u.mutation.SetChildID(v)
	return _u
}

// SetNillableChildID sets the "child_id" field if the given value is not nil.
func (_u *DependencyUpdate) SetNillableChildID(v *string) *DependencyUpdate {
	if v != nil {
		_u.SetChildID(*v)
	}
	return _u
}

// SetDependencyType sets the "dependency_type" field.
func (_u *DependencyUpdate) SetDependencyType(v dependency.DependencyType) *DependencyUpdate {
	_u.mutation.SetDependencyType(v)
	return _u
}

// SetNillableDependencyType sets the "dependency_type" field if the given value is not nil.
func (_u *DependencyUpdate) SetNillableDependencyType(v *dependency.DependencyType) *DependencyUpdate {
	if v != nil {
		_u.SetDependencyType(*v)
	}
	return _u
}

// SetParentPackageID sets the "parent_package" edge to the MediaPackage entity by ID.
func (_u *DependencyUpdate) SetParentPackageID(id string) *DependencyUpdate {
	_u.mutation.SetParentPackageID(id)
	return _u
}

// SetParentPackage sets the "parent_package" edge to the MediaPackage entity.
func (_u *DependencyUpdate) SetParentPackage(v *MediaPackage) *DependencyUpdate {
	return _u.SetParentPackageID(v.ID)
}

// SetChildPackageID sets the "child_package" edge to the MediaPackage entity by ID.
func (_u *DependencyUpdate) SetChildPackageID(id string) *DependencyUpdate {
	_u.mutation.SetChildPackageID(id)
	return _u
}

// SetChildPackage sets the "child_package" edge to the MediaPackage entity.
func (_u *DependencyUpdate) SetChildPackage(v *MediaPackage) *DependencyUpdate {
	return _u.SetChildPackageID(v.ID)
}

// Mutation returns the DependencyMutation object of the builder.
func (_u *DependencyUpdate) Mutation() *DependencyMutation {
	return _u.mutation
}

// ClearParentPackage clears the "parent_package" edge to the MediaPackage entity.
func (_u *DependencyUpdate) ClearParentPackage() *DependencyUpdate {
	_u.mutation.ClearParentPackage()
	return _u
}

// ClearChildPackage clears the "child_package" edge to the MediaPackage entity.
func (_u *DependencyUpdate) ClearChildPackage() *DependencyUpdate {
	_u.mutation.ClearChildPackage()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DependencyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DependencyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DependencyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DependencyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DependencyUpdate) check() error {
	if v, ok := _u.mutation.ParentID(); ok {
		if err := dependency.ParentIDValidator(v); err != nil {
			return &ValidationError{Name: "parent_id", err: fmt.Errorf(`ent: validator failed for field "Dependency.parent_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChildID(); ok {
		if err := dependency.ChildIDValidator(v); err != nil {
			return &ValidationError{Name: "child_id", err: fmt.Errorf(`ent: validator failed for field "Dependency.child_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DependencyType(); ok {
		if err := dependency.DependencyTypeValidator(v); err != nil {
			return &ValidationError{Name: "dependency_type", err: fmt.Errorf(`ent: validator failed for field "Dependency.dependency_type": %w`, err)}
		}
	}
	if _u.mutation.ParentPackageCleared() && len(_u.mutation.ParentPackageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Dependency.parent_package"`)
	}
	if _u.mutation.ChildPackageCleared() && len(_u.mutation.ChildPackageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Dependency.child_package"`)
	}
	return nil
}

func (_u *DependencyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dependency.Table, dependency.Columns, sqlgraph.NewFieldSpec(dependency.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DependencyType(); ok {
		_spec.SetField(dependency.FieldDependencyType, field.TypeEnum, value)
	}
	if _u.mutation.ParentPackageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dependency.ParentPackageTable,
			Columns: []string{dependency.ParentPackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediapackage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentPackageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dependency.ParentPackageTable,
			Columns: []string{dependency.ParentPackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediapackage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildPackageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dependency.ChildPackageTable,
			Columns: []string{dependency.ChildPackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediapackage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildPackageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dependency.ChildPackageTable,
			Columns: []string{dependency.ChildPackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediapackage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dependency.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DependencyUpdateOne is the builder for updating a single Dependency entity.
type DependencyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DependencyMutation
}

// SetParentID sets the "parent_id" field.
func (_u *DependencyUpdateOne) SetParentID(v string) *DependencyUpdateOne {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *DependencyUpdateOne) SetNillableParentID(v *string) *DependencyUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// SetChildID sets the "child_id" field.
func (_u *DependencyUpdateOne) SetChildID(v string) *DependencyUpdateOne {
	_u.mutation.SetChildID(v)
	return _u
}

// SetNillableChildID sets the "child_id" field if the given value is not nil.
func (_u *DependencyUpdateOne) SetNillableChildID(v *string) *DependencyUpdateOne {
	if v != nil {
		_u.SetChildID(*v)
	}
	return _u
}

// SetDependencyType sets the "dependency_type" field.
func (_u *DependencyUpdateOne) SetDependencyType(v dependency.DependencyType) *DependencyUpdateOne {
	_u.mutation.SetDependencyType(v)
	return _u
}

// SetNillableDependencyType sets the "dependency_type" field if the given value is not nil.
func (_u *DependencyUpdateOne) SetNillableDependencyType(v *dependency.DependencyType) *DependencyUpdateOne {
	if v != nil {
		_u.SetDependencyType(*v)
	}
	return _u
}

// SetParentPackageID sets the "parent_package" edge to the MediaPackage entity by ID.
func (_u *DependencyUpdateOne) SetParentPackageID(id string) *DependencyUpdateOne {
	_u.mutation.SetParentPackageID(id)
	return _u
}

// SetParentPackage sets the "parent_package" edge to the MediaPackage entity.
func (_u *DependencyUpdateOne) SetParentPackage(v *MediaPackage) *DependencyUpdateOne {
	return _u.SetParentPackageID(v.ID)
}

// SetChildPackageID sets the "child_package" edge to the MediaPackage entity by ID.
func (_u *DependencyUpdateOne) SetChildPackageID(id string) *DependencyUpdateOne {
	_u.mutation.SetChildPackageID(id)
	return _u
}

// SetChildPackage sets the "child_package" edge to the MediaPackage entity.
func (_u *DependencyUpdateOne) SetChildPackage(v *MediaPackage) *DependencyUpdateOne {
	return _u.SetChildPackageID(v.ID)
}

// Mutation returns the DependencyMutation object of the builder.
func (_u *DependencyUpdateOne) Mutation() *DependencyMutation {
	return _u.mutation
}

// ClearParentPackage clears the "parent_package" edge to the MediaPackage entity.
func (_u *DependencyUpdateOne) ClearParentPackage() *DependencyUpdateOne {
	_u.mutation.ClearParentPackage()
	return _u
}

// ClearChildPackage clears the "child_package" edge to the MediaPackage entity.
func (_u *DependencyUpdateOne) ClearChildPackage() *DependencyUpdateOne {
	_u.mutation.ClearChildPackage()
	return _u
}

// Where appends a list predicates to the DependencyUpdate builder.
func (_u *DependencyUpdateOne) Where(ps ...predicate.Dependency) *DependencyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DependencyUpdateOne) Select(field string, fields ...string) *DependencyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Dependency entity.
func (_u *DependencyUpdateOne) Save(ctx context.Context) (*Dependency, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DependencyUpdateOne) SaveX(ctx context.Context) *Dependency {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DependencyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DependencyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DependencyUpdateOne) check() error {
	if v, ok := _u.mutation.ParentID(); ok {
		if err := dependency.ParentIDValidator(v); err != nil {
			return &ValidationError{Name: "parent_id", err: fmt.Errorf(`ent: validator failed for field "Dependency.parent_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChildID(); ok {
		if err := dependency.ChildIDValidator(v); err != nil {
			return &ValidationError{Name: "child_id", err: fmt.Errorf(`ent: validator failed for field "Dependency.child_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DependencyType(); ok {
		if err := dependency.DependencyTypeValidator(v); err != nil {
			return &ValidationError{Name: "dependency_type", err: fmt.Errorf(`ent: validator failed for field "Dependency.dependency_type": %w`, err)}
		}
	}
	if _u.mutation.ParentPackageCleared() && len(_u.mutation.ParentPackageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Dependency.parent_package"`)
	}
	if _u.mutation.ChildPackageCleared() && len(_u.mutation.ChildPackageIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Dependency.child_package"`)
	}
	return nil
}

func (_u *DependencyUpdateOne) sqlSave(ctx context.Context) (_node *Dependency, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dependency.Table, dependency.Columns, sqlgraph.NewFieldSpec(dependency.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Dependency.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dependency.FieldID)
		for _, f := range fields {
			if !dependency.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dependency.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DependencyType(); ok {
		_spec.SetField(dependency.FieldDependencyType, field.TypeEnum, value)
	}
	if _u.mutation.ParentPackageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dependency.ParentPackageTable,
			Columns: []string{dependency.ParentPackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediapackage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentPackageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dependency.ParentPackageTable,
			Columns: []string{dependency.ParentPackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediapackage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildPackageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dependency.ChildPackageTable,
			Columns: []string{dependency.ChildPackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediapackage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildPackageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dependency.ChildPackageTable,
			Columns: []string{dependency.ChildPackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediapackage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Dependency{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dependency.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
