// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/elliot14A/fincher/internal/turso/ent/dependency"
	"github.com/elliot14A/fincher/internal/turso/ent/mediapackage"
)

// Dependency is the model entity for the Dependency schema.
type Dependency struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ParentID holds the value of the "parent_id" field.
	ParentID string `json:"parent_id,omitempty"`
	// ChildID holds the value of the "child_id" field.
	ChildID string `json:"child_id,omitempty"`
	// DependencyType holds the value of the "dependency_type" field.
	DependencyType dependency.DependencyType `json:"dependency_type,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DependencyQuery when eager-loading is set.
	Edges        DependencyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DependencyEdges holds the relations/edges for other nodes in the graph.
type DependencyEdges struct {
	// ParentPackage holds the value of the parent_package edge.
	ParentPackage *MediaPackage `json:"parent_package,omitempty"`
	// ChildPackage holds the value of the child_package edge.
	ChildPackage *MediaPackage `json:"child_package,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ParentPackageOrErr returns the ParentPackage value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DependencyEdges) ParentPackageOrErr() (*MediaPackage, error) {
	if e.ParentPackage != nil {
		return e.ParentPackage, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: mediapackage.Label}
	}
	return nil, &NotLoadedError{edge: "parent_package"}
}

// ChildPackageOrErr returns the ChildPackage value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DependencyEdges) ChildPackageOrErr() (*MediaPackage, error) {
	if e.ChildPackage != nil {
		return e.ChildPackage, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: mediapackage.Label}
	}
	return nil, &NotLoadedError{edge: "child_package"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Dependency) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dependency.FieldID, dependency.FieldParentID, dependency.FieldChildID, dependency.FieldDependencyType:
			values[i] = new(sql.NullString)
		case dependency.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Dependency fields.
func (_m *Dependency) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dependency.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case dependency.FieldParentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = value.String
			}
		case dependency.FieldChildID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field child_id", values[i])
			} else if value.Valid {
				_m.ChildID = value.String
			}
		case dependency.FieldDependencyType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dependency_type", values[i])
			} else if value.Valid {
				_m.DependencyType = dependency.DependencyType(value.String)
			}
		case dependency.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Dependency.
// This includes values selected through modifiers, order, etc.
func (_m *Dependency) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryParentPackage queries the "parent_package" edge of the Dependency entity.
func (_m *Dependency) QueryParentPackage() *MediaPackageQuery {
	return NewDependencyClient(_m.config).QueryParentPackage(_m)
}

// QueryChildPackage queries the "child_package" edge of the Dependency entity.
func (_m *Dependency) QueryChildPackage() *MediaPackageQuery {
	return NewDependencyClient(_m.config).QueryChildPackage(_m)
}

// Update returns a builder for updating this Dependency.
// Note that you need to call Dependency.Unwrap() before calling this method if this Dependency
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Dependency) Update() *DependencyUpdateOne {
	return NewDependencyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Dependency entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Dependency) Unwrap() *Dependency {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Dependency is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Dependency) String() string {
	var builder strings.Builder
	builder.WriteString("Dependency(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("parent_id=")
	builder.WriteString(_m.ParentID)
	builder.WriteString(", ")
	builder.WriteString("child_id=")
	builder.WriteString(_m.ChildID)
	builder.WriteString(", ")
	builder.WriteString("dependency_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.DependencyType))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Dependencies is a parsable slice of Dependency.
type Dependencies []*Dependency
