// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/elliot14A/fincher/internal/turso/ent/master"
	"github.com/elliot14A/fincher/internal/turso/ent/predicate"
	"github.com/elliot14A/fincher/internal/turso/ent/title"
)

// MasterUpdate is the builder for updating Master entities.
type MasterUpdate struct {
	config
	hooks    []Hook
	mutation *MasterMutation
}

// Where appends a list predicates to the MasterUpdate builder.
func (_u *MasterUpdate) Where(ps ...predicate.Master) *MasterUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitleID sets the "title_id" field.
func (_u *MasterUpdate) SetTitleID(v string) *MasterUpdate {
	_u.mutation.SetTitleID(v)
	return _u
}

// SetNillableTitleID sets the "title_id" field if the given value is not nil.
func (_u *MasterUpdate) SetNillableTitleID(v *string) *MasterUpdate {
	if v != nil {
		_u.SetTitleID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *MasterUpdate) SetVersion(v string) *MasterUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *MasterUpdate) SetNillableVersion(v *string) *MasterUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetSupersedesVersion sets the "supersedes_version" field.
func (_u *MasterUpdate) SetSupersedesVersion(v string) *MasterUpdate {
	_u.mutation.SetSupersedesVersion(v)
	return _u
}

// SetNillableSupersedesVersion sets the "supersedes_version" field if the given value is not nil.
func (_u *MasterUpdate) SetNillableSupersedesVersion(v *string) *MasterUpdate {
	if v != nil {
		_u.SetSupersedesVersion(*v)
	}
	return _u
}

// ClearSupersedesVersion clears the value of the "supersedes_version" field.
func (_u *MasterUpdate) ClearSupersedesVersion() *MasterUpdate {
	_u.mutation.ClearSupersedesVersion()
	return _u
}

// SetTitle sets the "title" edge to the Title entity.
func (_u *MasterUpdate) SetTitle(v *Title) *MasterUpdate {
	return _u.SetTitleID(v.ID)
}

// Mutation returns the MasterMutation object of the builder.
func (_u *MasterUpdate) Mutation() *MasterMutation {
	return _u.mutation
}

// ClearTitle clears the "title" edge to the Title entity.
func (_u *MasterUpdate) ClearTitle() *MasterUpdate {
	_u.mutation.ClearTitle()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MasterUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MasterUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MasterUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MasterUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MasterUpdate) check() error {
	if v, ok := _u.mutation.TitleID(); ok {
		if err := master.TitleIDValidator(v); err != nil {
			return &ValidationError{Name: "title_id", err: fmt.Errorf(`ent: validator failed for field "Master.title_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := master.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Master.version": %w`, err)}
		}
	}
	if _u.mutation.TitleCleared() && len(_u.mutation.TitleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Master.title"`)
	}
	return nil
}

func (_u *MasterUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(master.Table, master.Columns, sqlgraph.NewFieldSpec(master.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(master.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.SupersedesVersion(); ok {
		_spec.SetField(master.FieldSupersedesVersion, field.TypeString, value)
	}
	if _u.mutation.SupersedesVersionCleared() {
		_spec.ClearField(master.FieldSupersedesVersion, field.TypeString)
	}
	if _u.mutation.TitleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   master.TitleTable,
			Columns: []string{master.TitleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(title.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TitleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   master.TitleTable,
			Columns: []string{master.TitleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(title.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{master.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MasterUpdateOne is the builder for updating a single Master entity.
type MasterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MasterMutation
}

// SetTitleID sets the "title_id" field.
func (_u *MasterUpdateOne) SetTitleID(v string) *MasterUpdateOne {
	_u.mutation.SetTitleID(v)
	return _u
}

// SetNillableTitleID sets the "title_id" field if the given value is not nil.
func (_u *MasterUpdateOne) SetNillableTitleID(v *string) *MasterUpdateOne {
	if v != nil {
		_u.SetTitleID(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *MasterUpdateOne) SetVersion(v string) *MasterUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *MasterUpdateOne) SetNillableVersion(v *string) *MasterUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetSupersedesVersion sets the "supersedes_version" field.
func (_u *MasterUpdateOne) SetSupersedesVersion(v string) *MasterUpdateOne {
	_u.mutation.SetSupersedesVersion(v)
	return _u
}

// SetNillableSupersedesVersion sets the "supersedes_version" field if the given value is not nil.
func (_u *MasterUpdateOne) SetNillableSupersedesVersion(v *string) *MasterUpdateOne {
	if v != nil {
		_u.SetSupersedesVersion(*v)
	}
	return _u
}

// ClearSupersedesVersion clears the value of the "supersedes_version" field.
func (_u *MasterUpdateOne) ClearSupersedesVersion() *MasterUpdateOne {
	_u.mutation.ClearSupersedesVersion()
	return _u
}

// SetTitle sets the "title" edge to the Title entity.
func (_u *MasterUpdateOne) SetTitle(v *Title) *MasterUpdateOne {
	return _u.SetTitleID(v.ID)
}

// Mutation returns the MasterMutation object of the builder.
func (_u *MasterUpdateOne) Mutation() *MasterMutation {
	return _u.mutation
}

// ClearTitle clears the "title" edge to the Title entity.
func (_u *MasterUpdateOne) ClearTitle() *MasterUpdateOne {
	_u.mutation.ClearTitle()
	return _u
}

// Where appends a list predicates to the MasterUpdate builder.
func (_u *MasterUpdateOne) Where(ps ...predicate.Master) *MasterUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MasterUpdateOne) Select(field string, fields ...string) *MasterUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Master entity.
func (_u *MasterUpdateOne) Save(ctx context.Context) (*Master, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MasterUpdateOne) SaveX(ctx context.Context) *Master {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MasterUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MasterUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MasterUpdateOne) check() error {
	if v, ok := _u.mutation.TitleID(); ok {
		if err := master.TitleIDValidator(v); err != nil {
			return &ValidationError{Name: "title_id", err: fmt.Errorf(`ent: validator failed for field "Master.title_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := master.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Master.version": %w`, err)}
		}
	}
	if _u.mutation.TitleCleared() && len(_u.mutation.TitleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Master.title"`)
	}
	return nil
}

func (_u *MasterUpdateOne) sqlSave(ctx context.Context) (_node *Master, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(master.Table, master.Columns, sqlgraph.NewFieldSpec(master.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Master.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, master.FieldID)
		for _, f := range fields {
			if !master.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != master.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(master.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.SupersedesVersion(); ok {
		_spec.SetField(master.FieldSupersedesVersion, field.TypeString, value)
	}
	if _u.mutation.SupersedesVersionCleared() {
		_spec.ClearField(master.FieldSupersedesVersion, field.TypeString)
	}
	if _u.mutation.TitleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   master.TitleTable,
			Columns: []string{master.TitleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(title.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TitleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   master.TitleTable,
			Columns: []string{master.TitleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(title.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Master{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{master.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
