// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/elliot14A/fincher/internal/turso/ent/master"
	"github.com/elliot14A/fincher/internal/turso/ent/title"
)

// Master is the model entity for the Master schema.
type Master struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TitleID holds the value of the "title_id" field.
	TitleID string `json:"title_id,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// SupersedesVersion holds the value of the "supersedes_version" field.
	SupersedesVersion string `json:"supersedes_version,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MasterQuery when eager-loading is set.
	Edges        MasterEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MasterEdges holds the relations/edges for other nodes in the graph.
type MasterEdges struct {
	// Title holds the value of the title edge.
	Title *Title `json:"title,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TitleOrErr returns the Title value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MasterEdges) TitleOrErr() (*Title, error) {
	if e.Title != nil {
		return e.Title, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: title.Label}
	}
	return nil, &NotLoadedError{edge: "title"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Master) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case master.FieldID, master.FieldTitleID, master.FieldVersion, master.FieldSupersedesVersion:
			values[i] = new(sql.NullString)
		case master.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Master fields.
func (_m *Master) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case master.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case master.FieldTitleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title_id", values[i])
			} else if value.Valid {
				_m.TitleID = value.String
			}
		case master.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case master.FieldSupersedesVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field supersedes_version", values[i])
			} else if value.Valid {
				_m.SupersedesVersion = value.String
			}
		case master.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Master.
// This includes values selected through modifiers, order, etc.
func (_m *Master) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTitle queries the "title" edge of the Master entity.
func (_m *Master) QueryTitle() *TitleQuery {
	return NewMasterClient(_m.config).QueryTitle(_m)
}

// Update returns a builder for updating this Master.
// Note that you need to call Master.Unwrap() before calling this method if this Master
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Master) Update() *MasterUpdateOne {
	return NewMasterClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Master entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Master) Unwrap() *Master {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Master is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Master) String() string {
	var builder strings.Builder
	builder.WriteString("Master(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title_id=")
	builder.WriteString(_m.TitleID)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("supersedes_version=")
	builder.WriteString(_m.SupersedesVersion)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Masters is a parsable slice of Master.
type Masters []*Master
