// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/elliot14A/fincher/internal/turso/ent/dependency"
	"github.com/elliot14A/fincher/internal/turso/ent/mediapackage"
	"github.com/elliot14A/fincher/internal/turso/ent/predicate"
	"github.com/elliot14A/fincher/internal/turso/ent/title"
	"github.com/elliot14A/fincher/internal/turso/ent/vendor"
)

// MediaPackageUpdate is the builder for updating MediaPackage entities.
type MediaPackageUpdate struct {
	config
	hooks    []Hook
	mutation *MediaPackageMutation
}

// Where appends a list predicates to the MediaPackageUpdate builder.
func (_u *MediaPackageUpdate) Where(ps ...predicate.MediaPackage) *MediaPackageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitleID sets the "title_id" field.
func (_u *MediaPackageUpdate) SetTitleID(v string) *MediaPackageUpdate {
	_u.mutation.SetTitleID(v)
	return _u
}

// SetNillableTitleID sets the "title_id" field if the given value is not nil.
func (_u *MediaPackageUpdate) SetNillableTitleID(v *string) *MediaPackageUpdate {
	if v != nil {
		_u.SetTitleID(*v)
	}
	return _u
}

// SetComponent sets the "component" field.
func (_u *MediaPackageUpdate) SetComponent(v mediapackage.Component) *MediaPackageUpdate {
	_u.mutation.SetComponent(v)
	return _u
}

// SetNillableComponent sets the "component" field if the given value is not nil.
func (_u *MediaPackageUpdate) SetNillableComponent(v *mediapackage.Component) *MediaPackageUpdate {
	if v != nil {
		_u.SetComponent(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *MediaPackageUpdate) SetLanguage(v string) *MediaPackageUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *MediaPackageUpdate) SetNillableLanguage(v *string) *MediaPackageUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *MediaPackageUpdate) SetVersion(v string) *MediaPackageUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *MediaPackageUpdate) SetNillableVersion(v *string) *MediaPackageUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetVendorID sets the "vendor_id" field.
func (_u *MediaPackageUpdate) SetVendorID(v string) *MediaPackageUpdate {
	_u.mutation.SetVendorID(v)
	return _u
}

// SetNillableVendorID sets the "vendor_id" field if the given value is not nil.
func (_u *MediaPackageUpdate) SetNillableVendorID(v *string) *MediaPackageUpdate {
	if v != nil {
		_u.SetVendorID(*v)
	}
	return _u
}

// SetDerivedFromMasterVersion sets the "derived_from_master_version" field.
func (_u *MediaPackageUpdate) SetDerivedFromMasterVersion(v string) *MediaPackageUpdate {
	_u.mutation.SetDerivedFromMasterVersion(v)
	return _u
}

// SetNillableDerivedFromMasterVersion sets the "derived_from_master_version" field if the given value is not nil.
func (_u *MediaPackageUpdate) SetNillableDerivedFromMasterVersion(v *string) *MediaPackageUpdate {
	if v != nil {
		_u.SetDerivedFromMasterVersion(*v)
	}
	return _u
}

// SetRedeliveryCount sets the "redelivery_count" field.
func (_u *MediaPackageUpdate) SetRedeliveryCount(v int) *MediaPackageUpdate {
	_u.mutation.ResetRedeliveryCount()
	_u.mutation.SetRedeliveryCount(v)
	return _u
}

// SetNillableRedeliveryCount sets the "redelivery_count" field if the given value is not nil.
func (_u *MediaPackageUpdate) SetNillableRedeliveryCount(v *int) *MediaPackageUpdate {
	if v != nil {
		_u.SetRedeliveryCount(*v)
	}
	return _u
}

// AddRedeliveryCount adds value to the "redelivery_count" field.
func (_u *MediaPackageUpdate) AddRedeliveryCount(v int) *MediaPackageUpdate {
	_u.mutation.AddRedeliveryCount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *MediaPackageUpdate) SetStatus(v mediapackage.Status) *MediaPackageUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MediaPackageUpdate) SetNillableStatus(v *mediapackage.Status) *MediaPackageUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaPackageUpdate) SetUpdatedAt(v time.Time) *MediaPackageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTitle sets the "title" edge to the Title entity.
func (_u *MediaPackageUpdate) SetTitle(v *Title) *MediaPackageUpdate {
	return _u.SetTitleID(v.ID)
}

// SetVendor sets the "vendor" edge to the Vendor entity.
func (_u *MediaPackageUpdate) SetVendor(v *Vendor) *MediaPackageUpdate {
	return _u.SetVendorID(v.ID)
}

// AddDependentChildIDs adds the "dependent_children" edge to the Dependency entity by IDs.
func (_u *MediaPackageUpdate) AddDependentChildIDs(ids ...string) *MediaPackageUpdate {
	_u.mutation.AddDependentChildIDs(ids...)
	return _u
}

// AddDependentChildren adds the "dependent_children" edges to the Dependency entity.
func (_u *MediaPackageUpdate) AddDependentChildren(v ...*Dependency) *MediaPackageUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDependentChildIDs(ids...)
}

// AddParentDependencyIDs adds the "parent_dependencies" edge to the Dependency entity by IDs.
func (_u *MediaPackageUpdate) AddParentDependencyIDs(ids ...string) *MediaPackageUpdate {
	_u.mutation.AddParentDependencyIDs(ids...)
	return _u
}

// AddParentDependencies adds the "parent_dependencies" edges to the Dependency entity.
func (_u *MediaPackageUpdate) AddParentDependencies(v ...*Dependency) *MediaPackageUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParentDependencyIDs(ids...)
}

// Mutation returns the MediaPackageMutation object of the builder.
func (_u *MediaPackageUpdate) Mutation() *MediaPackageMutation {
	return _u.mutation
}

// ClearTitle clears the "title" edge to the Title entity.
func (_u *MediaPackageUpdate) ClearTitle() *MediaPackageUpdate {
	_u.mutation.ClearTitle()
	return _u
}

// ClearVendor clears the "vendor" edge to the Vendor entity.
func (_u *MediaPackageUpdate) ClearVendor() *MediaPackageUpdate {
	_u.mutation.ClearVendor()
	return _u
}

// ClearDependentChildren clears all "dependent_children" edges to the Dependency entity.
func (_u *MediaPackageUpdate) ClearDependentChildren() *MediaPackageUpdate {
	_u.mutation.ClearDependentChildren()
	return _u
}

// RemoveDependentChildIDs removes the "dependent_children" edge to Dependency entities by IDs.
func (_u *MediaPackageUpdate) RemoveDependentChildIDs(ids ...string) *MediaPackageUpdate {
	_u.mutation.RemoveDependentChildIDs(ids...)
	return _u
}

// RemoveDependentChildren removes "dependent_children" edges to Dependency entities.
func (_u *MediaPackageUpdate) RemoveDependentChildren(v ...*Dependency) *MediaPackageUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDependentChildIDs(ids...)
}

// ClearParentDependencies clears all "parent_dependencies" edges to the Dependency entity.
func (_u *MediaPackageUpdate) ClearParentDependencies() *MediaPackageUpdate {
	_u.mutation.ClearParentDependencies()
	return _u
}

// RemoveParentDependencyIDs removes the "parent_dependencies" edge to Dependency entities by IDs.
func (_u *MediaPackageUpdate) RemoveParentDependencyIDs(ids ...string) *MediaPackageUpdate {
	_u.mutation.RemoveParentDependencyIDs(ids...)
	return _u
}

// RemoveParentDependencies removes "parent_dependencies" edges to Dependency entities.
func (_u *MediaPackageUpdate) RemoveParentDependencies(v ...*Dependency) *MediaPackageUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParentDependencyIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MediaPackageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaPackageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MediaPackageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaPackageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaPackageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mediapackage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaPackageUpdate) check() error {
	if v, ok := _u.mutation.TitleID(); ok {
		if err := mediapackage.TitleIDValidator(v); err != nil {
			return &ValidationError{Name: "title_id", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.title_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Component(); ok {
		if err := mediapackage.ComponentValidator(v); err != nil {
			return &ValidationError{Name: "component", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.component": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := mediapackage.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.language": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := mediapackage.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VendorID(); ok {
		if err := mediapackage.VendorIDValidator(v); err != nil {
			return &ValidationError{Name: "vendor_id", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.vendor_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DerivedFromMasterVersion(); ok {
		if err := mediapackage.DerivedFromMasterVersionValidator(v); err != nil {
			return &ValidationError{Name: "derived_from_master_version", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.derived_from_master_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RedeliveryCount(); ok {
		if err := mediapackage.RedeliveryCountValidator(v); err != nil {
			return &ValidationError{Name: "redelivery_count", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.redelivery_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := mediapackage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.status": %w`, err)}
		}
	}
	if _u.mutation.TitleCleared() && len(_u.mutation.TitleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MediaPackage.title"`)
	}
	if _u.mutation.VendorCleared() && len(_u.mutation.VendorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MediaPackage.vendor"`)
	}
	return nil
}

func (_u *MediaPackageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediapackage.Table, mediapackage.Columns, sqlgraph.NewFieldSpec(mediapackage.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Component(); ok {
		_spec.SetField(mediapackage.FieldComponent, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(mediapackage.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(mediapackage.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.DerivedFromMasterVersion(); ok {
		_spec.SetField(mediapackage.FieldDerivedFromMasterVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedeliveryCount(); ok {
		_spec.SetField(mediapackage.FieldRedeliveryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRedeliveryCount(); ok {
		_spec.AddField(mediapackage.FieldRedeliveryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mediapackage.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mediapackage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TitleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediapackage.TitleTable,
			Columns: []string{mediapackage.TitleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(title.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TitleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediapackage.TitleTable,
			Columns: []string{mediapackage.TitleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(title.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VendorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediapackage.VendorTable,
			Columns: []string{mediapackage.VendorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vendor.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VendorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediapackage.VendorTable,
			Columns: []string{mediapackage.VendorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vendor.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DependentChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediapackage.DependentChildrenTable,
			Columns: []string{mediapackage.DependentChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dependency.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDependentChildrenIDs(); len(nodes) > 0 && !_u.mutation.DependentChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediapackage.DependentChildrenTable,
			Columns: []string{mediapackage.DependentChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dependency.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DependentChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediapackage.DependentChildrenTable,
			Columns: []string{mediapackage.DependentChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dependency.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentDependenciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediapackage.ParentDependenciesTable,
			Columns: []string{mediapackage.ParentDependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dependency.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParentDependenciesIDs(); len(nodes) > 0 && !_u.mutation.ParentDependenciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediapackage.ParentDependenciesTable,
			Columns: []string{mediapackage.ParentDependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dependency.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentDependenciesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediapackage.ParentDependenciesTable,
			Columns: []string{mediapackage.ParentDependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dependency.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediapackage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MediaPackageUpdateOne is the builder for updating a single MediaPackage entity.
type MediaPackageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaPackageMutation
}

// SetTitleID sets the "title_id" field.
func (_u *MediaPackageUpdateOne) SetTitleID(v string) *MediaPackageUpdateOne {
	_u.mutation.SetTitleID(v)
	return _u
}

// SetNillableTitleID sets the "title_id" field if the given value is not nil.
func (_u *MediaPackageUpdateOne) SetNillableTitleID(v *string) *MediaPackageUpdateOne {
	if v != nil {
		_u.SetTitleID(*v)
	}
	return _u
}

// SetComponent sets the "component" field.
func (_u *MediaPackageUpdateOne) SetComponent(v mediapackage.Component) *MediaPackageUpdateOne {
	_u.mutation.SetComponent(v)
	return _u
}

// SetNillableComponent sets the "component" field if the given value is not nil.
func (_u *MediaPackageUpdateOne) SetNillableComponent(v *mediapackage.Component) *MediaPackageUpdateOne {
	if v != nil {
		_u.SetComponent(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *MediaPackageUpdateOne) SetLanguage(v string) *MediaPackageUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *MediaPackageUpdateOne) SetNillableLanguage(v *string) *MediaPackageUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *MediaPackageUpdateOne) SetVersion(v string) *MediaPackageUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *MediaPackageUpdateOne) SetNillableVersion(v *string) *MediaPackageUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetVendorID sets the "vendor_id" field.
func (_u *MediaPackageUpdateOne) SetVendorID(v string) *MediaPackageUpdateOne {
	_u.mutation.SetVendorID(v)
	return _u
}

// SetNillableVendorID sets the "vendor_id" field if the given value is not nil.
func (_u *MediaPackageUpdateOne) SetNillableVendorID(v *string) *MediaPackageUpdateOne {
	if v != nil {
		_u.SetVendorID(*v)
	}
	return _u
}

// SetDerivedFromMasterVersion sets the "derived_from_master_version" field.
func (_u *MediaPackageUpdateOne) SetDerivedFromMasterVersion(v string) *MediaPackageUpdateOne {
	_u.mutation.SetDerivedFromMasterVersion(v)
	return _u
}

// SetNillableDerivedFromMasterVersion sets the "derived_from_master_version" field if the given value is not nil.
func (_u *MediaPackageUpdateOne) SetNillableDerivedFromMasterVersion(v *string) *MediaPackageUpdateOne {
	if v != nil {
		_u.SetDerivedFromMasterVersion(*v)
	}
	return _u
}

// SetRedeliveryCount sets the "redelivery_count" field.
func (_u *MediaPackageUpdateOne) SetRedeliveryCount(v int) *MediaPackageUpdateOne {
	_u.mutation.ResetRedeliveryCount()
	_u.mutation.SetRedeliveryCount(v)
	return _u
}

// SetNillableRedeliveryCount sets the "redelivery_count" field if the given value is not nil.
func (_u *MediaPackageUpdateOne) SetNillableRedeliveryCount(v *int) *MediaPackageUpdateOne {
	if v != nil {
		_u.SetRedeliveryCount(*v)
	}
	return _u
}

// AddRedeliveryCount adds value to the "redelivery_count" field.
func (_u *MediaPackageUpdateOne) AddRedeliveryCount(v int) *MediaPackageUpdateOne {
	_u.mutation.AddRedeliveryCount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *MediaPackageUpdateOne) SetStatus(v mediapackage.Status) *MediaPackageUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MediaPackageUpdateOne) SetNillableStatus(v *mediapackage.Status) *MediaPackageUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaPackageUpdateOne) SetUpdatedAt(v time.Time) *MediaPackageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTitle sets the "title" edge to the Title entity.
func (_u *MediaPackageUpdateOne) SetTitle(v *Title) *MediaPackageUpdateOne {
	return _u.SetTitleID(v.ID)
}

// SetVendor sets the "vendor" edge to the Vendor entity.
func (_u *MediaPackageUpdateOne) SetVendor(v *Vendor) *MediaPackageUpdateOne {
	return _u.SetVendorID(v.ID)
}

// AddDependentChildIDs adds the "dependent_children" edge to the Dependency entity by IDs.
func (_u *MediaPackageUpdateOne) AddDependentChildIDs(ids ...string) *MediaPackageUpdateOne {
	_u.mutation.AddDependentChildIDs(ids...)
	return _u
}

// AddDependentChildren adds the "dependent_children" edges to the Dependency entity.
func (_u *MediaPackageUpdateOne) AddDependentChildren(v ...*Dependency) *MediaPackageUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDependentChildIDs(ids...)
}

// AddParentDependencyIDs adds the "parent_dependencies" edge to the Dependency entity by IDs.
func (_u *MediaPackageUpdateOne) AddParentDependencyIDs(ids ...string) *MediaPackageUpdateOne {
	_u.mutation.AddParentDependencyIDs(ids...)
	return _u
}

// AddParentDependencies adds the "parent_dependencies" edges to the Dependency entity.
func (_u *MediaPackageUpdateOne) AddParentDependencies(v ...*Dependency) *MediaPackageUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParentDependencyIDs(ids...)
}

// Mutation returns the MediaPackageMutation object of the builder.
func (_u *MediaPackageUpdateOne) Mutation() *MediaPackageMutation {
	return _u.mutation
}

// ClearTitle clears the "title" edge to the Title entity.
func (_u *MediaPackageUpdateOne) ClearTitle() *MediaPackageUpdateOne {
	_u.mutation.ClearTitle()
	return _u
}

// ClearVendor clears the "vendor" edge to the Vendor entity.
func (_u *MediaPackageUpdateOne) ClearVendor() *MediaPackageUpdateOne {
	_u.mutation.ClearVendor()
	return _u
}

// ClearDependentChildren clears all "dependent_children" edges to the Dependency entity.
func (_u *MediaPackageUpdateOne) ClearDependentChildren() *MediaPackageUpdateOne {
	_u.mutation.ClearDependentChildren()
	return _u
}

// RemoveDependentChildIDs removes the "dependent_children" edge to Dependency entities by IDs.
func (_u *MediaPackageUpdateOne) RemoveDependentChildIDs(ids ...string) *MediaPackageUpdateOne {
	_u.mutation.RemoveDependentChildIDs(ids...)
	return _u
}

// RemoveDependentChildren removes "dependent_children" edges to Dependency entities.
func (_u *MediaPackageUpdateOne) RemoveDependentChildren(v ...*Dependency) *MediaPackageUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDependentChildIDs(ids...)
}

// ClearParentDependencies clears all "parent_dependencies" edges to the Dependency entity.
func (_u *MediaPackageUpdateOne) ClearParentDependencies() *MediaPackageUpdateOne {
	_u.mutation.ClearParentDependencies()
	return _u
}

// RemoveParentDependencyIDs removes the "parent_dependencies" edge to Dependency entities by IDs.
func (_u *MediaPackageUpdateOne) RemoveParentDependencyIDs(ids ...string) *MediaPackageUpdateOne {
	_u.mutation.RemoveParentDependencyIDs(ids...)
	return _u
}

// RemoveParentDependencies removes "parent_dependencies" edges to Dependency entities.
func (_u *MediaPackageUpdateOne) RemoveParentDependencies(v ...*Dependency) *MediaPackageUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParentDependencyIDs(ids...)
}

// Where appends a list predicates to the MediaPackageUpdate builder.
func (_u *MediaPackageUpdateOne) Where(ps ...predicate.MediaPackage) *MediaPackageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MediaPackageUpdateOne) Select(field string, fields ...string) *MediaPackageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MediaPackage entity.
func (_u *MediaPackageUpdateOne) Save(ctx context.Context) (*MediaPackage, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaPackageUpdateOne) SaveX(ctx context.Context) *MediaPackage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MediaPackageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaPackageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaPackageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mediapackage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaPackageUpdateOne) check() error {
	if v, ok := _u.mutation.TitleID(); ok {
		if err := mediapackage.TitleIDValidator(v); err != nil {
			return &ValidationError{Name: "title_id", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.title_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Component(); ok {
		if err := mediapackage.ComponentValidator(v); err != nil {
			return &ValidationError{Name: "component", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.component": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Language(); ok {
		if err := mediapackage.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.language": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := mediapackage.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VendorID(); ok {
		if err := mediapackage.VendorIDValidator(v); err != nil {
			return &ValidationError{Name: "vendor_id", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.vendor_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DerivedFromMasterVersion(); ok {
		if err := mediapackage.DerivedFromMasterVersionValidator(v); err != nil {
			return &ValidationError{Name: "derived_from_master_version", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.derived_from_master_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RedeliveryCount(); ok {
		if err := mediapackage.RedeliveryCountValidator(v); err != nil {
			return &ValidationError{Name: "redelivery_count", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.redelivery_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := mediapackage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.status": %w`, err)}
		}
	}
	if _u.mutation.TitleCleared() && len(_u.mutation.TitleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MediaPackage.title"`)
	}
	if _u.mutation.VendorCleared() && len(_u.mutation.VendorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MediaPackage.vendor"`)
	}
	return nil
}

func (_u *MediaPackageUpdateOne) sqlSave(ctx context.Context) (_node *MediaPackage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mediapackage.Table, mediapackage.Columns, sqlgraph.NewFieldSpec(mediapackage.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MediaPackage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mediapackage.FieldID)
		for _, f := range fields {
			if !mediapackage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mediapackage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Component(); ok {
		_spec.SetField(mediapackage.FieldComponent, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(mediapackage.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(mediapackage.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.DerivedFromMasterVersion(); ok {
		_spec.SetField(mediapackage.FieldDerivedFromMasterVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedeliveryCount(); ok {
		_spec.SetField(mediapackage.FieldRedeliveryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRedeliveryCount(); ok {
		_spec.AddField(mediapackage.FieldRedeliveryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mediapackage.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mediapackage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TitleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediapackage.TitleTable,
			Columns: []string{mediapackage.TitleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(title.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TitleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediapackage.TitleTable,
			Columns: []string{mediapackage.TitleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(title.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VendorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediapackage.VendorTable,
			Columns: []string{mediapackage.VendorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vendor.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VendorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediapackage.VendorTable,
			Columns: []string{mediapackage.VendorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vendor.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DependentChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediapackage.DependentChildrenTable,
			Columns: []string{mediapackage.DependentChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dependency.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDependentChildrenIDs(); len(nodes) > 0 && !_u.mutation.DependentChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediapackage.DependentChildrenTable,
			Columns: []string{mediapackage.DependentChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dependency.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DependentChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediapackage.DependentChildrenTable,
			Columns: []string{mediapackage.DependentChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dependency.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentDependenciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediapackage.ParentDependenciesTable,
			Columns: []string{mediapackage.ParentDependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dependency.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParentDependenciesIDs(); len(nodes) > 0 && !_u.mutation.ParentDependenciesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediapackage.ParentDependenciesTable,
			Columns: []string{mediapackage.ParentDependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dependency.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentDependenciesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediapackage.ParentDependenciesTable,
			Columns: []string{mediapackage.ParentDependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dependency.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MediaPackage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mediapackage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
