// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/elliot14A/fincher/internal/turso/ent/dependency"
	"github.com/elliot14A/fincher/internal/turso/ent/mediapackage"
	"github.com/elliot14A/fincher/internal/turso/ent/title"
	"github.com/elliot14A/fincher/internal/turso/ent/vendor"
)

// MediaPackageCreate is the builder for creating a MediaPackage entity.
type MediaPackageCreate struct {
	config
	mutation *MediaPackageMutation
	hooks    []Hook
}

// SetMetadata sets the "metadata" field.
func (_c *MediaPackageCreate) SetMetadata(v map[string]interface{}) *MediaPackageCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MediaPackageCreate) SetCreatedAt(v time.Time) *MediaPackageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MediaPackageCreate) SetNillableCreatedAt(v *time.Time) *MediaPackageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MediaPackageCreate) SetUpdatedAt(v time.Time) *MediaPackageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MediaPackageCreate) SetNillableUpdatedAt(v *time.Time) *MediaPackageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTitleID sets the "title_id" field.
func (_c *MediaPackageCreate) SetTitleID(v string) *MediaPackageCreate {
	_c.mutation.SetTitleID(v)
	return _c
}

// SetComponent sets the "component" field.
func (_c *MediaPackageCreate) SetComponent(v mediapackage.Component) *MediaPackageCreate {
	_c.mutation.SetComponent(v)
	return _c
}

// SetLanguage sets the "language" field.
func (_c *MediaPackageCreate) SetLanguage(v string) *MediaPackageCreate {
	_c.mutation.SetLanguage(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *MediaPackageCreate) SetVersion(v string) *MediaPackageCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetVendorID sets the "vendor_id" field.
func (_c *MediaPackageCreate) SetVendorID(v string) *MediaPackageCreate {
	_c.mutation.SetVendorID(v)
	return _c
}

// SetDerivedFromMasterVersion sets the "derived_from_master_version" field.
func (_c *MediaPackageCreate) SetDerivedFromMasterVersion(v string) *MediaPackageCreate {
	_c.mutation.SetDerivedFromMasterVersion(v)
	return _c
}

// SetRedeliveryCount sets the "redelivery_count" field.
func (_c *MediaPackageCreate) SetRedeliveryCount(v int) *MediaPackageCreate {
	_c.mutation.SetRedeliveryCount(v)
	return _c
}

// SetNillableRedeliveryCount sets the "redelivery_count" field if the given value is not nil.
func (_c *MediaPackageCreate) SetNillableRedeliveryCount(v *int) *MediaPackageCreate {
	if v != nil {
		_c.SetRedeliveryCount(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *MediaPackageCreate) SetStatus(v mediapackage.Status) *MediaPackageCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MediaPackageCreate) SetNillableStatus(v *mediapackage.Status) *MediaPackageCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MediaPackageCreate) SetID(v string) *MediaPackageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTitle sets the "title" edge to the Title entity.
func (_c *MediaPackageCreate) SetTitle(v *Title) *MediaPackageCreate {
	return _c.SetTitleID(v.ID)
}

// SetVendor sets the "vendor" edge to the Vendor entity.
func (_c *MediaPackageCreate) SetVendor(v *Vendor) *MediaPackageCreate {
	return _c.SetVendorID(v.ID)
}

// AddDependentChildIDs adds the "dependent_children" edge to the Dependency entity by IDs.
func (_c *MediaPackageCreate) AddDependentChildIDs(ids ...string) *MediaPackageCreate {
	_c.mutation.AddDependentChildIDs(ids...)
	return _c
}

// AddDependentChildren adds the "dependent_children" edges to the Dependency entity.
func (_c *MediaPackageCreate) AddDependentChildren(v ...*Dependency) *MediaPackageCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDependentChildIDs(ids...)
}

// AddParentDependencyIDs adds the "parent_dependencies" edge to the Dependency entity by IDs.
func (_c *MediaPackageCreate) AddParentDependencyIDs(ids ...string) *MediaPackageCreate {
	_c.mutation.AddParentDependencyIDs(ids...)
	return _c
}

// AddParentDependencies adds the "parent_dependencies" edges to the Dependency entity.
func (_c *MediaPackageCreate) AddParentDependencies(v ...*Dependency) *MediaPackageCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddParentDependencyIDs(ids...)
}

// Mutation returns the MediaPackageMutation object of the builder.
func (_c *MediaPackageCreate) Mutation() *MediaPackageMutation {
	return _c.mutation
}

// Save creates the MediaPackage in the database.
func (_c *MediaPackageCreate) Save(ctx context.Context) (*MediaPackage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MediaPackageCreate) SaveX(ctx context.Context) *MediaPackage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaPackageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaPackageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MediaPackageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mediapackage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := mediapackage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.RedeliveryCount(); !ok {
		v := mediapackage.DefaultRedeliveryCount
		_c.mutation.SetRedeliveryCount(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := mediapackage.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MediaPackageCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MediaPackage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MediaPackage.updated_at"`)}
	}
	if _, ok := _c.mutation.TitleID(); !ok {
		return &ValidationError{Name: "title_id", err: errors.New(`ent: missing required field "MediaPackage.title_id"`)}
	}
	if v, ok := _c.mutation.TitleID(); ok {
		if err := mediapackage.TitleIDValidator(v); err != nil {
			return &ValidationError{Name: "title_id", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.title_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Component(); !ok {
		return &ValidationError{Name: "component", err: errors.New(`ent: missing required field "MediaPackage.component"`)}
	}
	if v, ok := _c.mutation.Component(); ok {
		if err := mediapackage.ComponentValidator(v); err != nil {
			return &ValidationError{Name: "component", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.component": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required field "MediaPackage.language"`)}
	}
	if v, ok := _c.mutation.Language(); ok {
		if err := mediapackage.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.language": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "MediaPackage.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := mediapackage.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VendorID(); !ok {
		return &ValidationError{Name: "vendor_id", err: errors.New(`ent: missing required field "MediaPackage.vendor_id"`)}
	}
	if v, ok := _c.mutation.VendorID(); ok {
		if err := mediapackage.VendorIDValidator(v); err != nil {
			return &ValidationError{Name: "vendor_id", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.vendor_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DerivedFromMasterVersion(); !ok {
		return &ValidationError{Name: "derived_from_master_version", err: errors.New(`ent: missing required field "MediaPackage.derived_from_master_version"`)}
	}
	if v, ok := _c.mutation.DerivedFromMasterVersion(); ok {
		if err := mediapackage.DerivedFromMasterVersionValidator(v); err != nil {
			return &ValidationError{Name: "derived_from_master_version", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.derived_from_master_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RedeliveryCount(); !ok {
		return &ValidationError{Name: "redelivery_count", err: errors.New(`ent: missing required field "MediaPackage.redelivery_count"`)}
	}
	if v, ok := _c.mutation.RedeliveryCount(); ok {
		if err := mediapackage.RedeliveryCountValidator(v); err != nil {
			return &ValidationError{Name: "redelivery_count", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.redelivery_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MediaPackage.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := mediapackage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := mediapackage.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "MediaPackage.id": %w`, err)}
		}
	}
	if len(_c.mutation.TitleIDs()) == 0 {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required edge "MediaPackage.title"`)}
	}
	if len(_c.mutation.VendorIDs()) == 0 {
		return &ValidationError{Name: "vendor", err: errors.New(`ent: missing required edge "MediaPackage.vendor"`)}
	}
	return nil
}

func (_c *MediaPackageCreate) sqlSave(ctx context.Context) (*MediaPackage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected MediaPackage.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MediaPackageCreate) createSpec() (*MediaPackage, *sqlgraph.CreateSpec) {
	var (
		_node = &MediaPackage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mediapackage.Table, sqlgraph.NewFieldSpec(mediapackage.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(mediapackage.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mediapackage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(mediapackage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Component(); ok {
		_spec.SetField(mediapackage.FieldComponent, field.TypeEnum, value)
		_node.Component = value
	}
	if value, ok := _c.mutation.Language(); ok {
		_spec.SetField(mediapackage.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(mediapackage.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.DerivedFromMasterVersion(); ok {
		_spec.SetField(mediapackage.FieldDerivedFromMasterVersion, field.TypeString, value)
		_node.DerivedFromMasterVersion = value
	}
	if value, ok := _c.mutation.RedeliveryCount(); ok {
		_spec.SetField(mediapackage.FieldRedeliveryCount, field.TypeInt, value)
		_node.RedeliveryCount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(mediapackage.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := _c.mutation.TitleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediapackage.TitleTable,
			Columns: []string{mediapackage.TitleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(title.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TitleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VendorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mediapackage.VendorTable,
			Columns: []string{mediapackage.VendorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(vendor.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.VendorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DependentChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediapackage.DependentChildrenTable,
			Columns: []string{mediapackage.DependentChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dependency.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParentDependenciesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mediapackage.ParentDependenciesTable,
			Columns: []string{mediapackage.ParentDependenciesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dependency.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MediaPackageCreateBulk is the builder for creating many MediaPackage entities in bulk.
type MediaPackageCreateBulk struct {
	config
	err      error
	builders []*MediaPackageCreate
}

// Save creates the MediaPackage entities in the database.
func (_c *MediaPackageCreateBulk) Save(ctx context.Context) ([]*MediaPackage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MediaPackage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MediaPackageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MediaPackageCreateBulk) SaveX(ctx context.Context) []*MediaPackage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaPackageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaPackageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
