// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/elliot14A/fincher/internal/turso/ent/predicate"
	"github.com/elliot14A/fincher/internal/turso/ent/run"
	"github.com/elliot14A/fincher/internal/turso/ent/step"
	"github.com/elliot14A/fincher/internal/turso/ent/wfresult"
)

// RunUpdate is the builder for updating Run entities.
type RunUpdate struct {
	config
	hooks    []Hook
	mutation *RunMutation
}

// Where appends a list predicates to the RunUpdate builder.
func (_u *RunUpdate) Where(ps ...predicate.Run) *RunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *RunUpdate) SetMetadata(v map[string]interface{}) *RunUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *RunUpdate) ClearMetadata() *RunUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RunUpdate) SetUpdatedAt(v time.Time) *RunUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTitleSlug sets the "title_slug" field.
func (_u *RunUpdate) SetTitleSlug(v string) *RunUpdate {
	_u.mutation.SetTitleSlug(v)
	return _u
}

// SetNillableTitleSlug sets the "title_slug" field if the given value is not nil.
func (_u *RunUpdate) SetNillableTitleSlug(v *string) *RunUpdate {
	if v != nil {
		_u.SetTitleSlug(*v)
	}
	return _u
}

// SetTrigger sets the "trigger" field.
func (_u *RunUpdate) SetTrigger(v string) *RunUpdate {
	_u.mutation.SetTrigger(v)
	return _u
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (_u *RunUpdate) SetNillableTrigger(v *string) *RunUpdate {
	if v != nil {
		_u.SetTrigger(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RunUpdate) SetStatus(v run.Status) *RunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RunUpdate) SetNillableStatus(v *run.Status) *RunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *RunUpdate) SetStartedAt(v time.Time) *RunUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *RunUpdate) SetNillableStartedAt(v *time.Time) *RunUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *RunUpdate) SetEndedAt(v time.Time) *RunUpdate {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *RunUpdate) SetNillableEndedAt(v *time.Time) *RunUpdate {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *RunUpdate) ClearEndedAt() *RunUpdate {
	_u.mutation.ClearEndedAt()
	return _u
}

// AddStepIDs adds the "steps" edge to the Step entity by IDs.
func (_u *RunUpdate) AddStepIDs(ids ...string) *RunUpdate {
	_u.mutation.AddStepIDs(ids...)
	return _u
}

// AddSteps adds the "steps" edges to the Step entity.
func (_u *RunUpdate) AddSteps(v ...*Step) *RunUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStepIDs(ids...)
}

// AddResultIDs adds the "results" edge to the WfResult entity by IDs.
func (_u *RunUpdate) AddResultIDs(ids ...string) *RunUpdate {
	_u.mutation.AddResultIDs(ids...)
	return _u
}

// AddResults adds the "results" edges to the WfResult entity.
func (_u *RunUpdate) AddResults(v ...*WfResult) *RunUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResultIDs(ids...)
}

// Mutation returns the RunMutation object of the builder.
func (_u *RunUpdate) Mutation() *RunMutation {
	return _u.mutation
}

// ClearSteps clears all "steps" edges to the Step entity.
func (_u *RunUpdate) ClearSteps() *RunUpdate {
	_u.mutation.ClearSteps()
	return _u
}

// RemoveStepIDs removes the "steps" edge to Step entities by IDs.
func (_u *RunUpdate) RemoveStepIDs(ids ...string) *RunUpdate {
	_u.mutation.RemoveStepIDs(ids...)
	return _u
}

// RemoveSteps removes "steps" edges to Step entities.
func (_u *RunUpdate) RemoveSteps(v ...*Step) *RunUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStepIDs(ids...)
}

// ClearResults clears all "results" edges to the WfResult entity.
func (_u *RunUpdate) ClearResults() *RunUpdate {
	_u.mutation.ClearResults()
	return _u
}

// RemoveResultIDs removes the "results" edge to WfResult entities by IDs.
func (_u *RunUpdate) RemoveResultIDs(ids ...string) *RunUpdate {
	_u.mutation.RemoveResultIDs(ids...)
	return _u
}

// RemoveResults removes "results" edges to WfResult entities.
func (_u *RunUpdate) RemoveResults(v ...*WfResult) *RunUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResultIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RunUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RunUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := run.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RunUpdate) check() error {
	if v, ok := _u.mutation.Trigger(); ok {
		if err := run.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`ent: validator failed for field "Run.trigger": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := run.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Run.status": %w`, err)}
		}
	}
	return nil
}

func (_u *RunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(run.Table, run.Columns, sqlgraph.NewFieldSpec(run.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(run.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(run.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(run.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TitleSlug(); ok {
		_spec.SetField(run.FieldTitleSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Trigger(); ok {
		_spec.SetField(run.FieldTrigger, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(run.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(run.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(run.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(run.FieldEndedAt, field.TypeTime)
	}
	if _u.mutation.StepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   run.StepsTable,
			Columns: []string{run.StepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStepsIDs(); len(nodes) > 0 && !_u.mutation.StepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   run.StepsTable,
			Columns: []string{run.StepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StepsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   run.StepsTable,
			Columns: []string{run.StepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   run.ResultsTable,
			Columns: []string{run.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wfresult.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResultsIDs(); len(nodes) > 0 && !_u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   run.ResultsTable,
			Columns: []string{run.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wfresult.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   run.ResultsTable,
			Columns: []string{run.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wfresult.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{run.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RunUpdateOne is the builder for updating a single Run entity.
type RunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RunMutation
}

// SetMetadata sets the "metadata" field.
func (_u *RunUpdateOne) SetMetadata(v map[string]interface{}) *RunUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *RunUpdateOne) ClearMetadata() *RunUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RunUpdateOne) SetUpdatedAt(v time.Time) *RunUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTitleSlug sets the "title_slug" field.
func (_u *RunUpdateOne) SetTitleSlug(v string) *RunUpdateOne {
	_u.mutation.SetTitleSlug(v)
	return _u
}

// SetNillableTitleSlug sets the "title_slug" field if the given value is not nil.
func (_u *RunUpdateOne) SetNillableTitleSlug(v *string) *RunUpdateOne {
	if v != nil {
		_u.SetTitleSlug(*v)
	}
	return _u
}

// SetTrigger sets the "trigger" field.
func (_u *RunUpdateOne) SetTrigger(v string) *RunUpdateOne {
	_u.mutation.SetTrigger(v)
	return _u
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (_u *RunUpdateOne) SetNillableTrigger(v *string) *RunUpdateOne {
	if v != nil {
		_u.SetTrigger(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RunUpdateOne) SetStatus(v run.Status) *RunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RunUpdateOne) SetNillableStatus(v *run.Status) *RunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *RunUpdateOne) SetStartedAt(v time.Time) *RunUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *RunUpdateOne) SetNillableStartedAt(v *time.Time) *RunUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *RunUpdateOne) SetEndedAt(v time.Time) *RunUpdateOne {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *RunUpdateOne) SetNillableEndedAt(v *time.Time) *RunUpdateOne {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *RunUpdateOne) ClearEndedAt() *RunUpdateOne {
	_u.mutation.ClearEndedAt()
	return _u
}

// AddStepIDs adds the "steps" edge to the Step entity by IDs.
func (_u *RunUpdateOne) AddStepIDs(ids ...string) *RunUpdateOne {
	_u.mutation.AddStepIDs(ids...)
	return _u
}

// AddSteps adds the "steps" edges to the Step entity.
func (_u *RunUpdateOne) AddSteps(v ...*Step) *RunUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStepIDs(ids...)
}

// AddResultIDs adds the "results" edge to the WfResult entity by IDs.
func (_u *RunUpdateOne) AddResultIDs(ids ...string) *RunUpdateOne {
	_u.mutation.AddResultIDs(ids...)
	return _u
}

// AddResults adds the "results" edges to the WfResult entity.
func (_u *RunUpdateOne) AddResults(v ...*WfResult) *RunUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResultIDs(ids...)
}

// Mutation returns the RunMutation object of the builder.
func (_u *RunUpdateOne) Mutation() *RunMutation {
	return _u.mutation
}

// ClearSteps clears all "steps" edges to the Step entity.
func (_u *RunUpdateOne) ClearSteps() *RunUpdateOne {
	_u.mutation.ClearSteps()
	return _u
}

// RemoveStepIDs removes the "steps" edge to Step entities by IDs.
func (_u *RunUpdateOne) RemoveStepIDs(ids ...string) *RunUpdateOne {
	_u.mutation.RemoveStepIDs(ids...)
	return _u
}

// RemoveSteps removes "steps" edges to Step entities.
func (_u *RunUpdateOne) RemoveSteps(v ...*Step) *RunUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStepIDs(ids...)
}

// ClearResults clears all "results" edges to the WfResult entity.
func (_u *RunUpdateOne) ClearResults() *RunUpdateOne {
	_u.mutation.ClearResults()
	return _u
}

// RemoveResultIDs removes the "results" edge to WfResult entities by IDs.
func (_u *RunUpdateOne) RemoveResultIDs(ids ...string) *RunUpdateOne {
	_u.mutation.RemoveResultIDs(ids...)
	return _u
}

// RemoveResults removes "results" edges to WfResult entities.
func (_u *RunUpdateOne) RemoveResults(v ...*WfResult) *RunUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResultIDs(ids...)
}

// Where appends a list predicates to the RunUpdate builder.
func (_u *RunUpdateOne) Where(ps ...predicate.Run) *RunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RunUpdateOne) Select(field string, fields ...string) *RunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Run entity.
func (_u *RunUpdateOne) Save(ctx context.Context) (*Run, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RunUpdateOne) SaveX(ctx context.Context) *Run {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RunUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := run.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RunUpdateOne) check() error {
	if v, ok := _u.mutation.Trigger(); ok {
		if err := run.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`ent: validator failed for field "Run.trigger": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := run.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Run.status": %w`, err)}
		}
	}
	return nil
}

func (_u *RunUpdateOne) sqlSave(ctx context.Context) (_node *Run, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(run.Table, run.Columns, sqlgraph.NewFieldSpec(run.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Run.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, run.FieldID)
		for _, f := range fields {
			if !run.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != run.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(run.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(run.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(run.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TitleSlug(); ok {
		_spec.SetField(run.FieldTitleSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Trigger(); ok {
		_spec.SetField(run.FieldTrigger, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(run.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(run.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(run.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(run.FieldEndedAt, field.TypeTime)
	}
	if _u.mutation.StepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   run.StepsTable,
			Columns: []string{run.StepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStepsIDs(); len(nodes) > 0 && !_u.mutation.StepsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   run.StepsTable,
			Columns: []string{run.StepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StepsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   run.StepsTable,
			Columns: []string{run.StepsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   run.ResultsTable,
			Columns: []string{run.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wfresult.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResultsIDs(); len(nodes) > 0 && !_u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   run.ResultsTable,
			Columns: []string{run.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wfresult.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   run.ResultsTable,
			Columns: []string{run.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wfresult.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Run{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{run.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
