// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/elliot14A/fincher/internal/turso/ent/delivery"
	"github.com/elliot14A/fincher/internal/turso/ent/dependency"
	"github.com/elliot14A/fincher/internal/turso/ent/master"
	"github.com/elliot14A/fincher/internal/turso/ent/mediapackage"
	"github.com/elliot14A/fincher/internal/turso/ent/run"
	"github.com/elliot14A/fincher/internal/turso/ent/schema"
	"github.com/elliot14A/fincher/internal/turso/ent/step"
	"github.com/elliot14A/fincher/internal/turso/ent/title"
	"github.com/elliot14A/fincher/internal/turso/ent/upload"
	"github.com/elliot14A/fincher/internal/turso/ent/vendor"
	"github.com/elliot14A/fincher/internal/turso/ent/wfresult"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	deliveryMixin := schema.Delivery{}.Mixin()
	deliveryMixinFields0 := deliveryMixin[0].Fields()
	_ = deliveryMixinFields0
	deliveryFields := schema.Delivery{}.Fields()
	_ = deliveryFields
	// deliveryDescCreatedAt is the schema descriptor for created_at field.
	deliveryDescCreatedAt := deliveryMixinFields0[2].Descriptor()
	// delivery.DefaultCreatedAt holds the default value on creation for the created_at field.
	delivery.DefaultCreatedAt = deliveryDescCreatedAt.Default.(func() time.Time)
	// deliveryDescUpdatedAt is the schema descriptor for updated_at field.
	deliveryDescUpdatedAt := deliveryMixinFields0[3].Descriptor()
	// delivery.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	delivery.DefaultUpdatedAt = deliveryDescUpdatedAt.Default.(func() time.Time)
	// delivery.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	delivery.UpdateDefaultUpdatedAt = deliveryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// deliveryDescTitleID is the schema descriptor for title_id field.
	deliveryDescTitleID := deliveryFields[0].Descriptor()
	// delivery.TitleIDValidator is a validator for the "title_id" field. It is called by the builders before save.
	delivery.TitleIDValidator = deliveryDescTitleID.Validators[0].(func(string) error)
	// deliveryDescCountry is the schema descriptor for country field.
	deliveryDescCountry := deliveryFields[1].Descriptor()
	// delivery.CountryValidator is a validator for the "country" field. It is called by the builders before save.
	delivery.CountryValidator = deliveryDescCountry.Validators[0].(func(string) error)
	// deliveryDescID is the schema descriptor for id field.
	deliveryDescID := deliveryMixinFields0[0].Descriptor()
	// delivery.IDValidator is a validator for the "id" field. It is called by the builders before save.
	delivery.IDValidator = deliveryDescID.Validators[0].(func(string) error)
	dependencyFields := schema.Dependency{}.Fields()
	_ = dependencyFields
	// dependencyDescParentID is the schema descriptor for parent_id field.
	dependencyDescParentID := dependencyFields[1].Descriptor()
	// dependency.ParentIDValidator is a validator for the "parent_id" field. It is called by the builders before save.
	dependency.ParentIDValidator = dependencyDescParentID.Validators[0].(func(string) error)
	// dependencyDescChildID is the schema descriptor for child_id field.
	dependencyDescChildID := dependencyFields[2].Descriptor()
	// dependency.ChildIDValidator is a validator for the "child_id" field. It is called by the builders before save.
	dependency.ChildIDValidator = dependencyDescChildID.Validators[0].(func(string) error)
	// dependencyDescCreatedAt is the schema descriptor for created_at field.
	dependencyDescCreatedAt := dependencyFields[4].Descriptor()
	// dependency.DefaultCreatedAt holds the default value on creation for the created_at field.
	dependency.DefaultCreatedAt = dependencyDescCreatedAt.Default.(func() time.Time)
	// dependencyDescID is the schema descriptor for id field.
	dependencyDescID := dependencyFields[0].Descriptor()
	// dependency.IDValidator is a validator for the "id" field. It is called by the builders before save.
	dependency.IDValidator = dependencyDescID.Validators[0].(func(string) error)
	masterFields := schema.Master{}.Fields()
	_ = masterFields
	// masterDescTitleID is the schema descriptor for title_id field.
	masterDescTitleID := masterFields[1].Descriptor()
	// master.TitleIDValidator is a validator for the "title_id" field. It is called by the builders before save.
	master.TitleIDValidator = masterDescTitleID.Validators[0].(func(string) error)
	// masterDescVersion is the schema descriptor for version field.
	masterDescVersion := masterFields[2].Descriptor()
	// master.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	master.VersionValidator = masterDescVersion.Validators[0].(func(string) error)
	// masterDescCreatedAt is the schema descriptor for created_at field.
	masterDescCreatedAt := masterFields[4].Descriptor()
	// master.DefaultCreatedAt holds the default value on creation for the created_at field.
	master.DefaultCreatedAt = masterDescCreatedAt.Default.(func() time.Time)
	// masterDescID is the schema descriptor for id field.
	masterDescID := masterFields[0].Descriptor()
	// master.IDValidator is a validator for the "id" field. It is called by the builders before save.
	master.IDValidator = masterDescID.Validators[0].(func(string) error)
	mediapackageMixin := schema.MediaPackage{}.Mixin()
	mediapackageMixinFields0 := mediapackageMixin[0].Fields()
	_ = mediapackageMixinFields0
	mediapackageFields := schema.MediaPackage{}.Fields()
	_ = mediapackageFields
	// mediapackageDescCreatedAt is the schema descriptor for created_at field.
	mediapackageDescCreatedAt := mediapackageMixinFields0[2].Descriptor()
	// mediapackage.DefaultCreatedAt holds the default value on creation for the created_at field.
	mediapackage.DefaultCreatedAt = mediapackageDescCreatedAt.Default.(func() time.Time)
	// mediapackageDescUpdatedAt is the schema descriptor for updated_at field.
	mediapackageDescUpdatedAt := mediapackageMixinFields0[3].Descriptor()
	// mediapackage.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	mediapackage.DefaultUpdatedAt = mediapackageDescUpdatedAt.Default.(func() time.Time)
	// mediapackage.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	mediapackage.UpdateDefaultUpdatedAt = mediapackageDescUpdatedAt.UpdateDefault.(func() time.Time)
	// mediapackageDescTitleID is the schema descriptor for title_id field.
	mediapackageDescTitleID := mediapackageFields[0].Descriptor()
	// mediapackage.TitleIDValidator is a validator for the "title_id" field. It is called by the builders before save.
	mediapackage.TitleIDValidator = mediapackageDescTitleID.Validators[0].(func(string) error)
	// mediapackageDescLanguage is the schema descriptor for language field.
	mediapackageDescLanguage := mediapackageFields[2].Descriptor()
	// mediapackage.LanguageValidator is a validator for the "language" field. It is called by the builders before save.
	mediapackage.LanguageValidator = mediapackageDescLanguage.Validators[0].(func(string) error)
	// mediapackageDescVersion is the schema descriptor for version field.
	mediapackageDescVersion := mediapackageFields[3].Descriptor()
	// mediapackage.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	mediapackage.VersionValidator = mediapackageDescVersion.Validators[0].(func(string) error)
	// mediapackageDescVendorID is the schema descriptor for vendor_id field.
	mediapackageDescVendorID := mediapackageFields[4].Descriptor()
	// mediapackage.VendorIDValidator is a validator for the "vendor_id" field. It is called by the builders before save.
	mediapackage.VendorIDValidator = mediapackageDescVendorID.Validators[0].(func(string) error)
	// mediapackageDescDerivedFromMasterVersion is the schema descriptor for derived_from_master_version field.
	mediapackageDescDerivedFromMasterVersion := mediapackageFields[5].Descriptor()
	// mediapackage.DerivedFromMasterVersionValidator is a validator for the "derived_from_master_version" field. It is called by the builders before save.
	mediapackage.DerivedFromMasterVersionValidator = mediapackageDescDerivedFromMasterVersion.Validators[0].(func(string) error)
	// mediapackageDescRedeliveryCount is the schema descriptor for redelivery_count field.
	mediapackageDescRedeliveryCount := mediapackageFields[6].Descriptor()
	// mediapackage.DefaultRedeliveryCount holds the default value on creation for the redelivery_count field.
	mediapackage.DefaultRedeliveryCount = mediapackageDescRedeliveryCount.Default.(int)
	// mediapackage.RedeliveryCountValidator is a validator for the "redelivery_count" field. It is called by the builders before save.
	mediapackage.RedeliveryCountValidator = mediapackageDescRedeliveryCount.Validators[0].(func(int) error)
	// mediapackageDescMarket is the schema descriptor for market field.
	mediapackageDescMarket := mediapackageFields[8].Descriptor()
	// mediapackage.DefaultMarket holds the default value on creation for the market field.
	mediapackage.DefaultMarket = mediapackageDescMarket.Default.(string)
	// mediapackageDescID is the schema descriptor for id field.
	mediapackageDescID := mediapackageMixinFields0[0].Descriptor()
	// mediapackage.IDValidator is a validator for the "id" field. It is called by the builders before save.
	mediapackage.IDValidator = mediapackageDescID.Validators[0].(func(string) error)
	runMixin := schema.Run{}.Mixin()
	runMixinFields0 := runMixin[0].Fields()
	_ = runMixinFields0
	runFields := schema.Run{}.Fields()
	_ = runFields
	// runDescCreatedAt is the schema descriptor for created_at field.
	runDescCreatedAt := runMixinFields0[2].Descriptor()
	// run.DefaultCreatedAt holds the default value on creation for the created_at field.
	run.DefaultCreatedAt = runDescCreatedAt.Default.(func() time.Time)
	// runDescUpdatedAt is the schema descriptor for updated_at field.
	runDescUpdatedAt := runMixinFields0[3].Descriptor()
	// run.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	run.DefaultUpdatedAt = runDescUpdatedAt.Default.(func() time.Time)
	// run.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	run.UpdateDefaultUpdatedAt = runDescUpdatedAt.UpdateDefault.(func() time.Time)
	// runDescTitleSlug is the schema descriptor for title_slug field.
	runDescTitleSlug := runFields[0].Descriptor()
	// run.DefaultTitleSlug holds the default value on creation for the title_slug field.
	run.DefaultTitleSlug = runDescTitleSlug.Default.(string)
	// runDescTrigger is the schema descriptor for trigger field.
	runDescTrigger := runFields[1].Descriptor()
	// run.TriggerValidator is a validator for the "trigger" field. It is called by the builders before save.
	run.TriggerValidator = runDescTrigger.Validators[0].(func(string) error)
	// runDescID is the schema descriptor for id field.
	runDescID := runMixinFields0[0].Descriptor()
	// run.IDValidator is a validator for the "id" field. It is called by the builders before save.
	run.IDValidator = runDescID.Validators[0].(func(string) error)
	stepMixin := schema.Step{}.Mixin()
	stepMixinFields0 := stepMixin[0].Fields()
	_ = stepMixinFields0
	stepFields := schema.Step{}.Fields()
	_ = stepFields
	// stepDescCreatedAt is the schema descriptor for created_at field.
	stepDescCreatedAt := stepMixinFields0[2].Descriptor()
	// step.DefaultCreatedAt holds the default value on creation for the created_at field.
	step.DefaultCreatedAt = stepDescCreatedAt.Default.(func() time.Time)
	// stepDescUpdatedAt is the schema descriptor for updated_at field.
	stepDescUpdatedAt := stepMixinFields0[3].Descriptor()
	// step.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	step.DefaultUpdatedAt = stepDescUpdatedAt.Default.(func() time.Time)
	// step.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	step.UpdateDefaultUpdatedAt = stepDescUpdatedAt.UpdateDefault.(func() time.Time)
	// stepDescRunID is the schema descriptor for run_id field.
	stepDescRunID := stepFields[0].Descriptor()
	// step.RunIDValidator is a validator for the "run_id" field. It is called by the builders before save.
	step.RunIDValidator = stepDescRunID.Validators[0].(func(string) error)
	// stepDescName is the schema descriptor for name field.
	stepDescName := stepFields[1].Descriptor()
	// step.NameValidator is a validator for the "name" field. It is called by the builders before save.
	step.NameValidator = stepDescName.Validators[0].(func(string) error)
	// stepDescID is the schema descriptor for id field.
	stepDescID := stepMixinFields0[0].Descriptor()
	// step.IDValidator is a validator for the "id" field. It is called by the builders before save.
	step.IDValidator = stepDescID.Validators[0].(func(string) error)
	titleMixin := schema.Title{}.Mixin()
	titleMixinFields0 := titleMixin[0].Fields()
	_ = titleMixinFields0
	titleFields := schema.Title{}.Fields()
	_ = titleFields
	// titleDescCreatedAt is the schema descriptor for created_at field.
	titleDescCreatedAt := titleMixinFields0[2].Descriptor()
	// title.DefaultCreatedAt holds the default value on creation for the created_at field.
	title.DefaultCreatedAt = titleDescCreatedAt.Default.(func() time.Time)
	// titleDescUpdatedAt is the schema descriptor for updated_at field.
	titleDescUpdatedAt := titleMixinFields0[3].Descriptor()
	// title.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	title.DefaultUpdatedAt = titleDescUpdatedAt.Default.(func() time.Time)
	// title.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	title.UpdateDefaultUpdatedAt = titleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// titleDescName is the schema descriptor for name field.
	titleDescName := titleFields[0].Descriptor()
	// title.NameValidator is a validator for the "name" field. It is called by the builders before save.
	title.NameValidator = titleDescName.Validators[0].(func(string) error)
	// titleDescSlug is the schema descriptor for slug field.
	titleDescSlug := titleFields[1].Descriptor()
	// title.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	title.SlugValidator = titleDescSlug.Validators[0].(func(string) error)
	// titleDescTerritories is the schema descriptor for territories field.
	titleDescTerritories := titleFields[4].Descriptor()
	// title.DefaultTerritories holds the default value on creation for the territories field.
	title.DefaultTerritories = titleDescTerritories.Default.(int)
	// title.TerritoriesValidator is a validator for the "territories" field. It is called by the builders before save.
	title.TerritoriesValidator = titleDescTerritories.Validators[0].(func(int) error)
	// titleDescCurrentMasterVersion is the schema descriptor for current_master_version field.
	titleDescCurrentMasterVersion := titleFields[5].Descriptor()
	// title.DefaultCurrentMasterVersion holds the default value on creation for the current_master_version field.
	title.DefaultCurrentMasterVersion = titleDescCurrentMasterVersion.Default.(string)
	// titleDescID is the schema descriptor for id field.
	titleDescID := titleMixinFields0[0].Descriptor()
	// title.IDValidator is a validator for the "id" field. It is called by the builders before save.
	title.IDValidator = titleDescID.Validators[0].(func(string) error)
	uploadFields := schema.Upload{}.Fields()
	_ = uploadFields
	// uploadDescFilename is the schema descriptor for filename field.
	uploadDescFilename := uploadFields[1].Descriptor()
	// upload.FilenameValidator is a validator for the "filename" field. It is called by the builders before save.
	upload.FilenameValidator = uploadDescFilename.Validators[0].(func(string) error)
	// uploadDescMimeType is the schema descriptor for mime_type field.
	uploadDescMimeType := uploadFields[2].Descriptor()
	// upload.MimeTypeValidator is a validator for the "mime_type" field. It is called by the builders before save.
	upload.MimeTypeValidator = uploadDescMimeType.Validators[0].(func(string) error)
	// uploadDescData is the schema descriptor for data field.
	uploadDescData := uploadFields[3].Descriptor()
	// upload.DataValidator is a validator for the "data" field. It is called by the builders before save.
	upload.DataValidator = uploadDescData.Validators[0].(func([]byte) error)
	// uploadDescSizeBytes is the schema descriptor for size_bytes field.
	uploadDescSizeBytes := uploadFields[4].Descriptor()
	// upload.SizeBytesValidator is a validator for the "size_bytes" field. It is called by the builders before save.
	upload.SizeBytesValidator = uploadDescSizeBytes.Validators[0].(func(int64) error)
	// uploadDescCreatedAt is the schema descriptor for created_at field.
	uploadDescCreatedAt := uploadFields[5].Descriptor()
	// upload.DefaultCreatedAt holds the default value on creation for the created_at field.
	upload.DefaultCreatedAt = uploadDescCreatedAt.Default.(func() time.Time)
	vendorMixin := schema.Vendor{}.Mixin()
	vendorMixinFields0 := vendorMixin[0].Fields()
	_ = vendorMixinFields0
	vendorFields := schema.Vendor{}.Fields()
	_ = vendorFields
	// vendorDescCreatedAt is the schema descriptor for created_at field.
	vendorDescCreatedAt := vendorMixinFields0[2].Descriptor()
	// vendor.DefaultCreatedAt holds the default value on creation for the created_at field.
	vendor.DefaultCreatedAt = vendorDescCreatedAt.Default.(func() time.Time)
	// vendorDescUpdatedAt is the schema descriptor for updated_at field.
	vendorDescUpdatedAt := vendorMixinFields0[3].Descriptor()
	// vendor.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	vendor.DefaultUpdatedAt = vendorDescUpdatedAt.Default.(func() time.Time)
	// vendor.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	vendor.UpdateDefaultUpdatedAt = vendorDescUpdatedAt.UpdateDefault.(func() time.Time)
	// vendorDescName is the schema descriptor for name field.
	vendorDescName := vendorFields[0].Descriptor()
	// vendor.NameValidator is a validator for the "name" field. It is called by the builders before save.
	vendor.NameValidator = vendorDescName.Validators[0].(func(string) error)
	// vendorDescSpecialty is the schema descriptor for specialty field.
	vendorDescSpecialty := vendorFields[1].Descriptor()
	// vendor.SpecialtyValidator is a validator for the "specialty" field. It is called by the builders before save.
	vendor.SpecialtyValidator = vendorDescSpecialty.Validators[0].(func(string) error)
	// vendorDescHourlyRateUsd is the schema descriptor for hourly_rate_usd field.
	vendorDescHourlyRateUsd := vendorFields[2].Descriptor()
	// vendor.DefaultHourlyRateUsd holds the default value on creation for the hourly_rate_usd field.
	vendor.DefaultHourlyRateUsd = vendorDescHourlyRateUsd.Default.(float64)
	// vendor.HourlyRateUsdValidator is a validator for the "hourly_rate_usd" field. It is called by the builders before save.
	vendor.HourlyRateUsdValidator = vendorDescHourlyRateUsd.Validators[0].(func(float64) error)
	// vendorDescTurnaroundHours is the schema descriptor for turnaround_hours field.
	vendorDescTurnaroundHours := vendorFields[3].Descriptor()
	// vendor.DefaultTurnaroundHours holds the default value on creation for the turnaround_hours field.
	vendor.DefaultTurnaroundHours = vendorDescTurnaroundHours.Default.(int)
	// vendor.TurnaroundHoursValidator is a validator for the "turnaround_hours" field. It is called by the builders before save.
	vendor.TurnaroundHoursValidator = vendorDescTurnaroundHours.Validators[0].(func(int) error)
	// vendorDescID is the schema descriptor for id field.
	vendorDescID := vendorMixinFields0[0].Descriptor()
	// vendor.IDValidator is a validator for the "id" field. It is called by the builders before save.
	vendor.IDValidator = vendorDescID.Validators[0].(func(string) error)
	wfresultMixin := schema.WfResult{}.Mixin()
	wfresultMixinFields0 := wfresultMixin[0].Fields()
	_ = wfresultMixinFields0
	wfresultFields := schema.WfResult{}.Fields()
	_ = wfresultFields
	// wfresultDescCreatedAt is the schema descriptor for created_at field.
	wfresultDescCreatedAt := wfresultMixinFields0[2].Descriptor()
	// wfresult.DefaultCreatedAt holds the default value on creation for the created_at field.
	wfresult.DefaultCreatedAt = wfresultDescCreatedAt.Default.(func() time.Time)
	// wfresultDescUpdatedAt is the schema descriptor for updated_at field.
	wfresultDescUpdatedAt := wfresultMixinFields0[3].Descriptor()
	// wfresult.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	wfresult.DefaultUpdatedAt = wfresultDescUpdatedAt.Default.(func() time.Time)
	// wfresult.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	wfresult.UpdateDefaultUpdatedAt = wfresultDescUpdatedAt.UpdateDefault.(func() time.Time)
	// wfresultDescRunID is the schema descriptor for run_id field.
	wfresultDescRunID := wfresultFields[0].Descriptor()
	// wfresult.RunIDValidator is a validator for the "run_id" field. It is called by the builders before save.
	wfresult.RunIDValidator = wfresultDescRunID.Validators[0].(func(string) error)
	// wfresultDescJudge is the schema descriptor for judge field.
	wfresultDescJudge := wfresultFields[2].Descriptor()
	// wfresult.JudgeValidator is a validator for the "judge" field. It is called by the builders before save.
	wfresult.JudgeValidator = wfresultDescJudge.Validators[0].(func(string) error)
	// wfresultDescOutcome is the schema descriptor for outcome field.
	wfresultDescOutcome := wfresultFields[3].Descriptor()
	// wfresult.OutcomeValidator is a validator for the "outcome" field. It is called by the builders before save.
	wfresult.OutcomeValidator = wfresultDescOutcome.Validators[0].(func(string) error)
	// wfresultDescRationale is the schema descriptor for rationale field.
	wfresultDescRationale := wfresultFields[4].Descriptor()
	// wfresult.DefaultRationale holds the default value on creation for the rationale field.
	wfresult.DefaultRationale = wfresultDescRationale.Default.(string)
	// wfresultDescAttempt is the schema descriptor for attempt field.
	wfresultDescAttempt := wfresultFields[5].Descriptor()
	// wfresult.DefaultAttempt holds the default value on creation for the attempt field.
	wfresult.DefaultAttempt = wfresultDescAttempt.Default.(int)
	// wfresult.AttemptValidator is a validator for the "attempt" field. It is called by the builders before save.
	wfresult.AttemptValidator = wfresultDescAttempt.Validators[0].(func(int) error)
	// wfresultDescID is the schema descriptor for id field.
	wfresultDescID := wfresultMixinFields0[0].Descriptor()
	// wfresult.IDValidator is a validator for the "id" field. It is called by the builders before save.
	wfresult.IDValidator = wfresultDescID.Validators[0].(func(string) error)
}
