// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/elliot14A/fincher/internal/turso/ent/predicate"
	"github.com/elliot14A/fincher/internal/turso/ent/run"
	"github.com/elliot14A/fincher/internal/turso/ent/step"
	"github.com/elliot14A/fincher/internal/turso/ent/wfresult"
)

// StepUpdate is the builder for updating Step entities.
type StepUpdate struct {
	config
	hooks    []Hook
	mutation *StepMutation
}

// Where appends a list predicates to the StepUpdate builder.
func (_u *StepUpdate) Where(ps ...predicate.Step) *StepUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *StepUpdate) SetMetadata(v map[string]interface{}) *StepUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *StepUpdate) ClearMetadata() *StepUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StepUpdate) SetUpdatedAt(v time.Time) *StepUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRunID sets the "run_id" field.
func (_u *StepUpdate) SetRunID(v string) *StepUpdate {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *StepUpdate) SetNillableRunID(v *string) *StepUpdate {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *StepUpdate) SetName(v string) *StepUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StepUpdate) SetNillableName(v *string) *StepUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *StepUpdate) SetStatus(v step.Status) *StepUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *StepUpdate) SetNillableStatus(v *step.Status) *StepUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *StepUpdate) SetStartedAt(v time.Time) *StepUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *StepUpdate) SetNillableStartedAt(v *time.Time) *StepUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *StepUpdate) SetEndedAt(v time.Time) *StepUpdate {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *StepUpdate) SetNillableEndedAt(v *time.Time) *StepUpdate {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *StepUpdate) ClearEndedAt() *StepUpdate {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetRun sets the "run" edge to the Run entity.
func (_u *StepUpdate) SetRun(v *Run) *StepUpdate {
	return _u.SetRunID(v.ID)
}

// AddResultIDs adds the "results" edge to the WfResult entity by IDs.
func (_u *StepUpdate) AddResultIDs(ids ...string) *StepUpdate {
	_u.mutation.AddResultIDs(ids...)
	return _u
}

// AddResults adds the "results" edges to the WfResult entity.
func (_u *StepUpdate) AddResults(v ...*WfResult) *StepUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResultIDs(ids...)
}

// Mutation returns the StepMutation object of the builder.
func (_u *StepUpdate) Mutation() *StepMutation {
	return _u.mutation
}

// ClearRun clears the "run" edge to the Run entity.
func (_u *StepUpdate) ClearRun() *StepUpdate {
	_u.mutation.ClearRun()
	return _u
}

// ClearResults clears all "results" edges to the WfResult entity.
func (_u *StepUpdate) ClearResults() *StepUpdate {
	_u.mutation.ClearResults()
	return _u
}

// RemoveResultIDs removes the "results" edge to WfResult entities by IDs.
func (_u *StepUpdate) RemoveResultIDs(ids ...string) *StepUpdate {
	_u.mutation.RemoveResultIDs(ids...)
	return _u
}

// RemoveResults removes "results" edges to WfResult entities.
func (_u *StepUpdate) RemoveResults(v ...*WfResult) *StepUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResultIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StepUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StepUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StepUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StepUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StepUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := step.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StepUpdate) check() error {
	if v, ok := _u.mutation.RunID(); ok {
		if err := step.RunIDValidator(v); err != nil {
			return &ValidationError{Name: "run_id", err: fmt.Errorf(`ent: validator failed for field "Step.run_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := step.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Step.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := step.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Step.status": %w`, err)}
		}
	}
	if _u.mutation.RunCleared() && len(_u.mutation.RunIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Step.run"`)
	}
	return nil
}

func (_u *StepUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(step.Table, step.Columns, sqlgraph.NewFieldSpec(step.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(step.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(step.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(step.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(step.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(step.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(step.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(step.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(step.FieldEndedAt, field.TypeTime)
	}
	if _u.mutation.RunCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   step.RunTable,
			Columns: []string{step.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(run.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   step.RunTable,
			Columns: []string{step.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(run.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   step.ResultsTable,
			Columns: []string{step.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wfresult.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResultsIDs(); len(nodes) > 0 && !_u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   step.ResultsTable,
			Columns: []string{step.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wfresult.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   step.ResultsTable,
			Columns: []string{step.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wfresult.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{step.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StepUpdateOne is the builder for updating a single Step entity.
type StepUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StepMutation
}

// SetMetadata sets the "metadata" field.
func (_u *StepUpdateOne) SetMetadata(v map[string]interface{}) *StepUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *StepUpdateOne) ClearMetadata() *StepUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StepUpdateOne) SetUpdatedAt(v time.Time) *StepUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRunID sets the "run_id" field.
func (_u *StepUpdateOne) SetRunID(v string) *StepUpdateOne {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *StepUpdateOne) SetNillableRunID(v *string) *StepUpdateOne {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *StepUpdateOne) SetName(v string) *StepUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StepUpdateOne) SetNillableName(v *string) *StepUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *StepUpdateOne) SetStatus(v step.Status) *StepUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *StepUpdateOne) SetNillableStatus(v *step.Status) *StepUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *StepUpdateOne) SetStartedAt(v time.Time) *StepUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *StepUpdateOne) SetNillableStartedAt(v *time.Time) *StepUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *StepUpdateOne) SetEndedAt(v time.Time) *StepUpdateOne {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *StepUpdateOne) SetNillableEndedAt(v *time.Time) *StepUpdateOne {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *StepUpdateOne) ClearEndedAt() *StepUpdateOne {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetRun sets the "run" edge to the Run entity.
func (_u *StepUpdateOne) SetRun(v *Run) *StepUpdateOne {
	return _u.SetRunID(v.ID)
}

// AddResultIDs adds the "results" edge to the WfResult entity by IDs.
func (_u *StepUpdateOne) AddResultIDs(ids ...string) *StepUpdateOne {
	_u.mutation.AddResultIDs(ids...)
	return _u
}

// AddResults adds the "results" edges to the WfResult entity.
func (_u *StepUpdateOne) AddResults(v ...*WfResult) *StepUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResultIDs(ids...)
}

// Mutation returns the StepMutation object of the builder.
func (_u *StepUpdateOne) Mutation() *StepMutation {
	return _u.mutation
}

// ClearRun clears the "run" edge to the Run entity.
func (_u *StepUpdateOne) ClearRun() *StepUpdateOne {
	_u.mutation.ClearRun()
	return _u
}

// ClearResults clears all "results" edges to the WfResult entity.
func (_u *StepUpdateOne) ClearResults() *StepUpdateOne {
	_u.mutation.ClearResults()
	return _u
}

// RemoveResultIDs removes the "results" edge to WfResult entities by IDs.
func (_u *StepUpdateOne) RemoveResultIDs(ids ...string) *StepUpdateOne {
	_u.mutation.RemoveResultIDs(ids...)
	return _u
}

// RemoveResults removes "results" edges to WfResult entities.
func (_u *StepUpdateOne) RemoveResults(v ...*WfResult) *StepUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResultIDs(ids...)
}

// Where appends a list predicates to the StepUpdate builder.
func (_u *StepUpdateOne) Where(ps ...predicate.Step) *StepUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StepUpdateOne) Select(field string, fields ...string) *StepUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Step entity.
func (_u *StepUpdateOne) Save(ctx context.Context) (*Step, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StepUpdateOne) SaveX(ctx context.Context) *Step {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StepUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StepUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StepUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := step.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StepUpdateOne) check() error {
	if v, ok := _u.mutation.RunID(); ok {
		if err := step.RunIDValidator(v); err != nil {
			return &ValidationError{Name: "run_id", err: fmt.Errorf(`ent: validator failed for field "Step.run_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := step.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Step.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := step.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Step.status": %w`, err)}
		}
	}
	if _u.mutation.RunCleared() && len(_u.mutation.RunIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Step.run"`)
	}
	return nil
}

func (_u *StepUpdateOne) sqlSave(ctx context.Context) (_node *Step, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(step.Table, step.Columns, sqlgraph.NewFieldSpec(step.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Step.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, step.FieldID)
		for _, f := range fields {
			if !step.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != step.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(step.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(step.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(step.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(step.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(step.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(step.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(step.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(step.FieldEndedAt, field.TypeTime)
	}
	if _u.mutation.RunCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   step.RunTable,
			Columns: []string{step.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(run.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   step.RunTable,
			Columns: []string{step.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(run.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   step.ResultsTable,
			Columns: []string{step.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wfresult.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResultsIDs(); len(nodes) > 0 && !_u.mutation.ResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   step.ResultsTable,
			Columns: []string{step.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wfresult.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   step.ResultsTable,
			Columns: []string{step.ResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(wfresult.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Step{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{step.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
