// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/elliot14A/fincher/internal/turso/ent/predicate"
	"github.com/elliot14A/fincher/internal/turso/ent/upload"
)

// UploadUpdate is the builder for updating Upload entities.
type UploadUpdate struct {
	config
	hooks    []Hook
	mutation *UploadMutation
}

// Where appends a list predicates to the UploadUpdate builder.
func (_u *UploadUpdate) Where(ps ...predicate.Upload) *UploadUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetFilename sets the "filename" field.
func (_u *UploadUpdate) SetFilename(v string) *UploadUpdate {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *UploadUpdate) SetNillableFilename(v *string) *UploadUpdate {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *UploadUpdate) SetMimeType(v string) *UploadUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *UploadUpdate) SetNillableMimeType(v *string) *UploadUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetData sets the "data" field.
func (_u *UploadUpdate) SetData(v []byte) *UploadUpdate {
	_u.mutation.SetData(v)
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *UploadUpdate) SetSizeBytes(v int64) *UploadUpdate {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *UploadUpdate) SetNillableSizeBytes(v *int64) *UploadUpdate {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *UploadUpdate) AddSizeBytes(v int64) *UploadUpdate {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// Mutation returns the UploadMutation object of the builder.
func (_u *UploadUpdate) Mutation() *UploadMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UploadUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UploadUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UploadUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UploadUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UploadUpdate) check() error {
	if v, ok := _u.mutation.Filename(); ok {
		if err := upload.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "Upload.filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := upload.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "Upload.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Data(); ok {
		if err := upload.DataValidator(v); err != nil {
			return &ValidationError{Name: "data", err: fmt.Errorf(`ent: validator failed for field "Upload.data": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SizeBytes(); ok {
		if err := upload.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "Upload.size_bytes": %w`, err)}
		}
	}
	return nil
}

func (_u *UploadUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upload.Table, upload.Columns, sqlgraph.NewFieldSpec(upload.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(upload.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(upload.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(upload.FieldData, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(upload.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(upload.FieldSizeBytes, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UploadUpdateOne is the builder for updating a single Upload entity.
type UploadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UploadMutation
}

// SetFilename sets the "filename" field.
func (_u *UploadUpdateOne) SetFilename(v string) *UploadUpdateOne {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *UploadUpdateOne) SetNillableFilename(v *string) *UploadUpdateOne {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *UploadUpdateOne) SetMimeType(v string) *UploadUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *UploadUpdateOne) SetNillableMimeType(v *string) *UploadUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetData sets the "data" field.
func (_u *UploadUpdateOne) SetData(v []byte) *UploadUpdateOne {
	_u.mutation.SetData(v)
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *UploadUpdateOne) SetSizeBytes(v int64) *UploadUpdateOne {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *UploadUpdateOne) SetNillableSizeBytes(v *int64) *UploadUpdateOne {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *UploadUpdateOne) AddSizeBytes(v int64) *UploadUpdateOne {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// Mutation returns the UploadMutation object of the builder.
func (_u *UploadUpdateOne) Mutation() *UploadMutation {
	return _u.mutation
}

// Where appends a list predicates to the UploadUpdate builder.
func (_u *UploadUpdateOne) Where(ps ...predicate.Upload) *UploadUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UploadUpdateOne) Select(field string, fields ...string) *UploadUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Upload entity.
func (_u *UploadUpdateOne) Save(ctx context.Context) (*Upload, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UploadUpdateOne) SaveX(ctx context.Context) *Upload {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UploadUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UploadUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UploadUpdateOne) check() error {
	if v, ok := _u.mutation.Filename(); ok {
		if err := upload.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "Upload.filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := upload.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "Upload.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Data(); ok {
		if err := upload.DataValidator(v); err != nil {
			return &ValidationError{Name: "data", err: fmt.Errorf(`ent: validator failed for field "Upload.data": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SizeBytes(); ok {
		if err := upload.SizeBytesValidator(v); err != nil {
			return &ValidationError{Name: "size_bytes", err: fmt.Errorf(`ent: validator failed for field "Upload.size_bytes": %w`, err)}
		}
	}
	return nil
}

func (_u *UploadUpdateOne) sqlSave(ctx context.Context) (_node *Upload, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upload.Table, upload.Columns, sqlgraph.NewFieldSpec(upload.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Upload.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upload.FieldID)
		for _, f := range fields {
			if !upload.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upload.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(upload.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(upload.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(upload.FieldData, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(upload.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(upload.FieldSizeBytes, field.TypeInt64, value)
	}
	_node = &Upload{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
