// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/elliot14A/fincher/internal/turso/ent/mediapackage"
	"github.com/elliot14A/fincher/internal/turso/ent/vendor"
)

// VendorCreate is the builder for creating a Vendor entity.
type VendorCreate struct {
	config
	mutation *VendorMutation
	hooks    []Hook
}

// SetMetadata sets the "metadata" field.
func (_c *VendorCreate) SetMetadata(v map[string]interface{}) *VendorCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VendorCreate) SetCreatedAt(v time.Time) *VendorCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VendorCreate) SetNillableCreatedAt(v *time.Time) *VendorCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VendorCreate) SetUpdatedAt(v time.Time) *VendorCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VendorCreate) SetNillableUpdatedAt(v *time.Time) *VendorCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *VendorCreate) SetName(v string) *VendorCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetComponents sets the "components" field.
func (_c *VendorCreate) SetComponents(v []string) *VendorCreate {
	_c.mutation.SetComponents(v)
	return _c
}

// SetMarkets sets the "markets" field.
func (_c *VendorCreate) SetMarkets(v []string) *VendorCreate {
	_c.mutation.SetMarkets(v)
	return _c
}

// SetHourlyRateUsd sets the "hourly_rate_usd" field.
func (_c *VendorCreate) SetHourlyRateUsd(v float64) *VendorCreate {
	_c.mutation.SetHourlyRateUsd(v)
	return _c
}

// SetNillableHourlyRateUsd sets the "hourly_rate_usd" field if the given value is not nil.
func (_c *VendorCreate) SetNillableHourlyRateUsd(v *float64) *VendorCreate {
	if v != nil {
		_c.SetHourlyRateUsd(*v)
	}
	return _c
}

// SetTurnaroundHours sets the "turnaround_hours" field.
func (_c *VendorCreate) SetTurnaroundHours(v int) *VendorCreate {
	_c.mutation.SetTurnaroundHours(v)
	return _c
}

// SetNillableTurnaroundHours sets the "turnaround_hours" field if the given value is not nil.
func (_c *VendorCreate) SetNillableTurnaroundHours(v *int) *VendorCreate {
	if v != nil {
		_c.SetTurnaroundHours(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *VendorCreate) SetID(v string) *VendorCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddPackageIDs adds the "packages" edge to the MediaPackage entity by IDs.
func (_c *VendorCreate) AddPackageIDs(ids ...string) *VendorCreate {
	_c.mutation.AddPackageIDs(ids...)
	return _c
}

// AddPackages adds the "packages" edges to the MediaPackage entity.
func (_c *VendorCreate) AddPackages(v ...*MediaPackage) *VendorCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPackageIDs(ids...)
}

// Mutation returns the VendorMutation object of the builder.
func (_c *VendorCreate) Mutation() *VendorMutation {
	return _c.mutation
}

// Save creates the Vendor in the database.
func (_c *VendorCreate) Save(ctx context.Context) (*Vendor, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VendorCreate) SaveX(ctx context.Context) *Vendor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VendorCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VendorCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VendorCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := vendor.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := vendor.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.HourlyRateUsd(); !ok {
		v := vendor.DefaultHourlyRateUsd
		_c.mutation.SetHourlyRateUsd(v)
	}
	if _, ok := _c.mutation.TurnaroundHours(); !ok {
		v := vendor.DefaultTurnaroundHours
		_c.mutation.SetTurnaroundHours(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VendorCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Vendor.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Vendor.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Vendor.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := vendor.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Vendor.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Components(); !ok {
		return &ValidationError{Name: "components", err: errors.New(`ent: missing required field "Vendor.components"`)}
	}
	if _, ok := _c.mutation.Markets(); !ok {
		return &ValidationError{Name: "markets", err: errors.New(`ent: missing required field "Vendor.markets"`)}
	}
	if _, ok := _c.mutation.HourlyRateUsd(); !ok {
		return &ValidationError{Name: "hourly_rate_usd", err: errors.New(`ent: missing required field "Vendor.hourly_rate_usd"`)}
	}
	if v, ok := _c.mutation.HourlyRateUsd(); ok {
		if err := vendor.HourlyRateUsdValidator(v); err != nil {
			return &ValidationError{Name: "hourly_rate_usd", err: fmt.Errorf(`ent: validator failed for field "Vendor.hourly_rate_usd": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TurnaroundHours(); !ok {
		return &ValidationError{Name: "turnaround_hours", err: errors.New(`ent: missing required field "Vendor.turnaround_hours"`)}
	}
	if v, ok := _c.mutation.TurnaroundHours(); ok {
		if err := vendor.TurnaroundHoursValidator(v); err != nil {
			return &ValidationError{Name: "turnaround_hours", err: fmt.Errorf(`ent: validator failed for field "Vendor.turnaround_hours": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := vendor.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Vendor.id": %w`, err)}
		}
	}
	return nil
}

func (_c *VendorCreate) sqlSave(ctx context.Context) (*Vendor, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Vendor.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VendorCreate) createSpec() (*Vendor, *sqlgraph.CreateSpec) {
	var (
		_node = &Vendor{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(vendor.Table, sqlgraph.NewFieldSpec(vendor.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(vendor.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(vendor.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(vendor.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(vendor.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Components(); ok {
		_spec.SetField(vendor.FieldComponents, field.TypeJSON, value)
		_node.Components = value
	}
	if value, ok := _c.mutation.Markets(); ok {
		_spec.SetField(vendor.FieldMarkets, field.TypeJSON, value)
		_node.Markets = value
	}
	if value, ok := _c.mutation.HourlyRateUsd(); ok {
		_spec.SetField(vendor.FieldHourlyRateUsd, field.TypeFloat64, value)
		_node.HourlyRateUsd = value
	}
	if value, ok := _c.mutation.TurnaroundHours(); ok {
		_spec.SetField(vendor.FieldTurnaroundHours, field.TypeInt, value)
		_node.TurnaroundHours = value
	}
	if nodes := _c.mutation.PackagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   vendor.PackagesTable,
			Columns: []string{vendor.PackagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediapackage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// VendorCreateBulk is the builder for creating many Vendor entities in bulk.
type VendorCreateBulk struct {
	config
	err      error
	builders []*VendorCreate
}

// Save creates the Vendor entities in the database.
func (_c *VendorCreateBulk) Save(ctx context.Context) ([]*Vendor, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Vendor, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VendorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VendorCreateBulk) SaveX(ctx context.Context) []*Vendor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VendorCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VendorCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
