// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/elliot14A/fincher/internal/turso/ent/predicate"
	"github.com/elliot14A/fincher/internal/turso/ent/run"
	"github.com/elliot14A/fincher/internal/turso/ent/step"
	"github.com/elliot14A/fincher/internal/turso/ent/wfresult"
)

// WfResultUpdate is the builder for updating WfResult entities.
type WfResultUpdate struct {
	config
	hooks    []Hook
	mutation *WfResultMutation
}

// Where appends a list predicates to the WfResultUpdate builder.
func (_u *WfResultUpdate) Where(ps ...predicate.WfResult) *WfResultUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *WfResultUpdate) SetMetadata(v map[string]interface{}) *WfResultUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *WfResultUpdate) ClearMetadata() *WfResultUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WfResultUpdate) SetUpdatedAt(v time.Time) *WfResultUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRunID sets the "run_id" field.
func (_u *WfResultUpdate) SetRunID(v string) *WfResultUpdate {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *WfResultUpdate) SetNillableRunID(v *string) *WfResultUpdate {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// SetStepID sets the "step_id" field.
func (_u *WfResultUpdate) SetStepID(v string) *WfResultUpdate {
	_u.mutation.SetStepID(v)
	return _u
}

// SetNillableStepID sets the "step_id" field if the given value is not nil.
func (_u *WfResultUpdate) SetNillableStepID(v *string) *WfResultUpdate {
	if v != nil {
		_u.SetStepID(*v)
	}
	return _u
}

// ClearStepID clears the value of the "step_id" field.
func (_u *WfResultUpdate) ClearStepID() *WfResultUpdate {
	_u.mutation.ClearStepID()
	return _u
}

// SetJudge sets the "judge" field.
func (_u *WfResultUpdate) SetJudge(v string) *WfResultUpdate {
	_u.mutation.SetJudge(v)
	return _u
}

// SetNillableJudge sets the "judge" field if the given value is not nil.
func (_u *WfResultUpdate) SetNillableJudge(v *string) *WfResultUpdate {
	if v != nil {
		_u.SetJudge(*v)
	}
	return _u
}

// SetOutcome sets the "outcome" field.
func (_u *WfResultUpdate) SetOutcome(v string) *WfResultUpdate {
	_u.mutation.SetOutcome(v)
	return _u
}

// SetNillableOutcome sets the "outcome" field if the given value is not nil.
func (_u *WfResultUpdate) SetNillableOutcome(v *string) *WfResultUpdate {
	if v != nil {
		_u.SetOutcome(*v)
	}
	return _u
}

// SetRationale sets the "rationale" field.
func (_u *WfResultUpdate) SetRationale(v string) *WfResultUpdate {
	_u.mutation.SetRationale(v)
	return _u
}

// SetNillableRationale sets the "rationale" field if the given value is not nil.
func (_u *WfResultUpdate) SetNillableRationale(v *string) *WfResultUpdate {
	if v != nil {
		_u.SetRationale(*v)
	}
	return _u
}

// SetAttempt sets the "attempt" field.
func (_u *WfResultUpdate) SetAttempt(v int) *WfResultUpdate {
	_u.mutation.ResetAttempt()
	_u.mutation.SetAttempt(v)
	return _u
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (_u *WfResultUpdate) SetNillableAttempt(v *int) *WfResultUpdate {
	if v != nil {
		_u.SetAttempt(*v)
	}
	return _u
}

// AddAttempt adds value to the "attempt" field.
func (_u *WfResultUpdate) AddAttempt(v int) *WfResultUpdate {
	_u.mutation.AddAttempt(v)
	return _u
}

// SetRun sets the "run" edge to the Run entity.
func (_u *WfResultUpdate) SetRun(v *Run) *WfResultUpdate {
	return _u.SetRunID(v.ID)
}

// SetStep sets the "step" edge to the Step entity.
func (_u *WfResultUpdate) SetStep(v *Step) *WfResultUpdate {
	return _u.SetStepID(v.ID)
}

// Mutation returns the WfResultMutation object of the builder.
func (_u *WfResultUpdate) Mutation() *WfResultMutation {
	return _u.mutation
}

// ClearRun clears the "run" edge to the Run entity.
func (_u *WfResultUpdate) ClearRun() *WfResultUpdate {
	_u.mutation.ClearRun()
	return _u
}

// ClearStep clears the "step" edge to the Step entity.
func (_u *WfResultUpdate) ClearStep() *WfResultUpdate {
	_u.mutation.ClearStep()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WfResultUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WfResultUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WfResultUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WfResultUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WfResultUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := wfresult.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WfResultUpdate) check() error {
	if v, ok := _u.mutation.RunID(); ok {
		if err := wfresult.RunIDValidator(v); err != nil {
			return &ValidationError{Name: "run_id", err: fmt.Errorf(`ent: validator failed for field "WfResult.run_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Judge(); ok {
		if err := wfresult.JudgeValidator(v); err != nil {
			return &ValidationError{Name: "judge", err: fmt.Errorf(`ent: validator failed for field "WfResult.judge": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Outcome(); ok {
		if err := wfresult.OutcomeValidator(v); err != nil {
			return &ValidationError{Name: "outcome", err: fmt.Errorf(`ent: validator failed for field "WfResult.outcome": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Attempt(); ok {
		if err := wfresult.AttemptValidator(v); err != nil {
			return &ValidationError{Name: "attempt", err: fmt.Errorf(`ent: validator failed for field "WfResult.attempt": %w`, err)}
		}
	}
	if _u.mutation.RunCleared() && len(_u.mutation.RunIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WfResult.run"`)
	}
	return nil
}

func (_u *WfResultUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wfresult.Table, wfresult.Columns, sqlgraph.NewFieldSpec(wfresult.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(wfresult.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(wfresult.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(wfresult.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Judge(); ok {
		_spec.SetField(wfresult.FieldJudge, field.TypeString, value)
	}
	if value, ok := _u.mutation.Outcome(); ok {
		_spec.SetField(wfresult.FieldOutcome, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rationale(); ok {
		_spec.SetField(wfresult.FieldRationale, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attempt(); ok {
		_spec.SetField(wfresult.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempt(); ok {
		_spec.AddField(wfresult.FieldAttempt, field.TypeInt, value)
	}
	if _u.mutation.RunCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wfresult.RunTable,
			Columns: []string{wfresult.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(run.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wfresult.RunTable,
			Columns: []string{wfresult.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(run.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StepCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wfresult.StepTable,
			Columns: []string{wfresult.StepColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StepIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wfresult.StepTable,
			Columns: []string{wfresult.StepColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wfresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WfResultUpdateOne is the builder for updating a single WfResult entity.
type WfResultUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WfResultMutation
}

// SetMetadata sets the "metadata" field.
func (_u *WfResultUpdateOne) SetMetadata(v map[string]interface{}) *WfResultUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *WfResultUpdateOne) ClearMetadata() *WfResultUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WfResultUpdateOne) SetUpdatedAt(v time.Time) *WfResultUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRunID sets the "run_id" field.
func (_u *WfResultUpdateOne) SetRunID(v string) *WfResultUpdateOne {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *WfResultUpdateOne) SetNillableRunID(v *string) *WfResultUpdateOne {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// SetStepID sets the "step_id" field.
func (_u *WfResultUpdateOne) SetStepID(v string) *WfResultUpdateOne {
	_u.mutation.SetStepID(v)
	return _u
}

// SetNillableStepID sets the "step_id" field if the given value is not nil.
func (_u *WfResultUpdateOne) SetNillableStepID(v *string) *WfResultUpdateOne {
	if v != nil {
		_u.SetStepID(*v)
	}
	return _u
}

// ClearStepID clears the value of the "step_id" field.
func (_u *WfResultUpdateOne) ClearStepID() *WfResultUpdateOne {
	_u.mutation.ClearStepID()
	return _u
}

// SetJudge sets the "judge" field.
func (_u *WfResultUpdateOne) SetJudge(v string) *WfResultUpdateOne {
	_u.mutation.SetJudge(v)
	return _u
}

// SetNillableJudge sets the "judge" field if the given value is not nil.
func (_u *WfResultUpdateOne) SetNillableJudge(v *string) *WfResultUpdateOne {
	if v != nil {
		_u.SetJudge(*v)
	}
	return _u
}

// SetOutcome sets the "outcome" field.
func (_u *WfResultUpdateOne) SetOutcome(v string) *WfResultUpdateOne {
	_u.mutation.SetOutcome(v)
	return _u
}

// SetNillableOutcome sets the "outcome" field if the given value is not nil.
func (_u *WfResultUpdateOne) SetNillableOutcome(v *string) *WfResultUpdateOne {
	if v != nil {
		_u.SetOutcome(*v)
	}
	return _u
}

// SetRationale sets the "rationale" field.
func (_u *WfResultUpdateOne) SetRationale(v string) *WfResultUpdateOne {
	_u.mutation.SetRationale(v)
	return _u
}

// SetNillableRationale sets the "rationale" field if the given value is not nil.
func (_u *WfResultUpdateOne) SetNillableRationale(v *string) *WfResultUpdateOne {
	if v != nil {
		_u.SetRationale(*v)
	}
	return _u
}

// SetAttempt sets the "attempt" field.
func (_u *WfResultUpdateOne) SetAttempt(v int) *WfResultUpdateOne {
	_u.mutation.ResetAttempt()
	_u.mutation.SetAttempt(v)
	return _u
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (_u *WfResultUpdateOne) SetNillableAttempt(v *int) *WfResultUpdateOne {
	if v != nil {
		_u.SetAttempt(*v)
	}
	return _u
}

// AddAttempt adds value to the "attempt" field.
func (_u *WfResultUpdateOne) AddAttempt(v int) *WfResultUpdateOne {
	_u.mutation.AddAttempt(v)
	return _u
}

// SetRun sets the "run" edge to the Run entity.
func (_u *WfResultUpdateOne) SetRun(v *Run) *WfResultUpdateOne {
	return _u.SetRunID(v.ID)
}

// SetStep sets the "step" edge to the Step entity.
func (_u *WfResultUpdateOne) SetStep(v *Step) *WfResultUpdateOne {
	return _u.SetStepID(v.ID)
}

// Mutation returns the WfResultMutation object of the builder.
func (_u *WfResultUpdateOne) Mutation() *WfResultMutation {
	return _u.mutation
}

// ClearRun clears the "run" edge to the Run entity.
func (_u *WfResultUpdateOne) ClearRun() *WfResultUpdateOne {
	_u.mutation.ClearRun()
	return _u
}

// ClearStep clears the "step" edge to the Step entity.
func (_u *WfResultUpdateOne) ClearStep() *WfResultUpdateOne {
	_u.mutation.ClearStep()
	return _u
}

// Where appends a list predicates to the WfResultUpdate builder.
func (_u *WfResultUpdateOne) Where(ps ...predicate.WfResult) *WfResultUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WfResultUpdateOne) Select(field string, fields ...string) *WfResultUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WfResult entity.
func (_u *WfResultUpdateOne) Save(ctx context.Context) (*WfResult, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WfResultUpdateOne) SaveX(ctx context.Context) *WfResult {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WfResultUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WfResultUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WfResultUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := wfresult.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WfResultUpdateOne) check() error {
	if v, ok := _u.mutation.RunID(); ok {
		if err := wfresult.RunIDValidator(v); err != nil {
			return &ValidationError{Name: "run_id", err: fmt.Errorf(`ent: validator failed for field "WfResult.run_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Judge(); ok {
		if err := wfresult.JudgeValidator(v); err != nil {
			return &ValidationError{Name: "judge", err: fmt.Errorf(`ent: validator failed for field "WfResult.judge": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Outcome(); ok {
		if err := wfresult.OutcomeValidator(v); err != nil {
			return &ValidationError{Name: "outcome", err: fmt.Errorf(`ent: validator failed for field "WfResult.outcome": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Attempt(); ok {
		if err := wfresult.AttemptValidator(v); err != nil {
			return &ValidationError{Name: "attempt", err: fmt.Errorf(`ent: validator failed for field "WfResult.attempt": %w`, err)}
		}
	}
	if _u.mutation.RunCleared() && len(_u.mutation.RunIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WfResult.run"`)
	}
	return nil
}

func (_u *WfResultUpdateOne) sqlSave(ctx context.Context) (_node *WfResult, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wfresult.Table, wfresult.Columns, sqlgraph.NewFieldSpec(wfresult.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WfResult.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wfresult.FieldID)
		for _, f := range fields {
			if !wfresult.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != wfresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(wfresult.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(wfresult.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(wfresult.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Judge(); ok {
		_spec.SetField(wfresult.FieldJudge, field.TypeString, value)
	}
	if value, ok := _u.mutation.Outcome(); ok {
		_spec.SetField(wfresult.FieldOutcome, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rationale(); ok {
		_spec.SetField(wfresult.FieldRationale, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attempt(); ok {
		_spec.SetField(wfresult.FieldAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempt(); ok {
		_spec.AddField(wfresult.FieldAttempt, field.TypeInt, value)
	}
	if _u.mutation.RunCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wfresult.RunTable,
			Columns: []string{wfresult.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(run.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wfresult.RunTable,
			Columns: []string{wfresult.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(run.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StepCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wfresult.StepTable,
			Columns: []string{wfresult.StepColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StepIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wfresult.StepTable,
			Columns: []string{wfresult.StepColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WfResult{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wfresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
