// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/elliot14A/fincher/internal/turso/ent/run"
	"github.com/elliot14A/fincher/internal/turso/ent/step"
	"github.com/elliot14A/fincher/internal/turso/ent/wfresult"
)

// WfResultCreate is the builder for creating a WfResult entity.
type WfResultCreate struct {
	config
	mutation *WfResultMutation
	hooks    []Hook
}

// SetMetadata sets the "metadata" field.
func (_c *WfResultCreate) SetMetadata(v map[string]interface{}) *WfResultCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WfResultCreate) SetCreatedAt(v time.Time) *WfResultCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WfResultCreate) SetNillableCreatedAt(v *time.Time) *WfResultCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WfResultCreate) SetUpdatedAt(v time.Time) *WfResultCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WfResultCreate) SetNillableUpdatedAt(v *time.Time) *WfResultCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRunID sets the "run_id" field.
func (_c *WfResultCreate) SetRunID(v string) *WfResultCreate {
	_c.mutation.SetRunID(v)
	return _c
}

// SetStepID sets the "step_id" field.
func (_c *WfResultCreate) SetStepID(v string) *WfResultCreate {
	_c.mutation.SetStepID(v)
	return _c
}

// SetNillableStepID sets the "step_id" field if the given value is not nil.
func (_c *WfResultCreate) SetNillableStepID(v *string) *WfResultCreate {
	if v != nil {
		_c.SetStepID(*v)
	}
	return _c
}

// SetJudge sets the "judge" field.
func (_c *WfResultCreate) SetJudge(v string) *WfResultCreate {
	_c.mutation.SetJudge(v)
	return _c
}

// SetOutcome sets the "outcome" field.
func (_c *WfResultCreate) SetOutcome(v string) *WfResultCreate {
	_c.mutation.SetOutcome(v)
	return _c
}

// SetRationale sets the "rationale" field.
func (_c *WfResultCreate) SetRationale(v string) *WfResultCreate {
	_c.mutation.SetRationale(v)
	return _c
}

// SetNillableRationale sets the "rationale" field if the given value is not nil.
func (_c *WfResultCreate) SetNillableRationale(v *string) *WfResultCreate {
	if v != nil {
		_c.SetRationale(*v)
	}
	return _c
}

// SetAttempt sets the "attempt" field.
func (_c *WfResultCreate) SetAttempt(v int) *WfResultCreate {
	_c.mutation.SetAttempt(v)
	return _c
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (_c *WfResultCreate) SetNillableAttempt(v *int) *WfResultCreate {
	if v != nil {
		_c.SetAttempt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WfResultCreate) SetID(v string) *WfResultCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetRun sets the "run" edge to the Run entity.
func (_c *WfResultCreate) SetRun(v *Run) *WfResultCreate {
	return _c.SetRunID(v.ID)
}

// SetStep sets the "step" edge to the Step entity.
func (_c *WfResultCreate) SetStep(v *Step) *WfResultCreate {
	return _c.SetStepID(v.ID)
}

// Mutation returns the WfResultMutation object of the builder.
func (_c *WfResultCreate) Mutation() *WfResultMutation {
	return _c.mutation
}

// Save creates the WfResult in the database.
func (_c *WfResultCreate) Save(ctx context.Context) (*WfResult, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WfResultCreate) SaveX(ctx context.Context) *WfResult {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WfResultCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WfResultCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WfResultCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := wfresult.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := wfresult.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Rationale(); !ok {
		v := wfresult.DefaultRationale
		_c.mutation.SetRationale(v)
	}
	if _, ok := _c.mutation.Attempt(); !ok {
		v := wfresult.DefaultAttempt
		_c.mutation.SetAttempt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WfResultCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WfResult.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WfResult.updated_at"`)}
	}
	if _, ok := _c.mutation.RunID(); !ok {
		return &ValidationError{Name: "run_id", err: errors.New(`ent: missing required field "WfResult.run_id"`)}
	}
	if v, ok := _c.mutation.RunID(); ok {
		if err := wfresult.RunIDValidator(v); err != nil {
			return &ValidationError{Name: "run_id", err: fmt.Errorf(`ent: validator failed for field "WfResult.run_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Judge(); !ok {
		return &ValidationError{Name: "judge", err: errors.New(`ent: missing required field "WfResult.judge"`)}
	}
	if v, ok := _c.mutation.Judge(); ok {
		if err := wfresult.JudgeValidator(v); err != nil {
			return &ValidationError{Name: "judge", err: fmt.Errorf(`ent: validator failed for field "WfResult.judge": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Outcome(); !ok {
		return &ValidationError{Name: "outcome", err: errors.New(`ent: missing required field "WfResult.outcome"`)}
	}
	if v, ok := _c.mutation.Outcome(); ok {
		if err := wfresult.OutcomeValidator(v); err != nil {
			return &ValidationError{Name: "outcome", err: fmt.Errorf(`ent: validator failed for field "WfResult.outcome": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Rationale(); !ok {
		return &ValidationError{Name: "rationale", err: errors.New(`ent: missing required field "WfResult.rationale"`)}
	}
	if _, ok := _c.mutation.Attempt(); !ok {
		return &ValidationError{Name: "attempt", err: errors.New(`ent: missing required field "WfResult.attempt"`)}
	}
	if v, ok := _c.mutation.Attempt(); ok {
		if err := wfresult.AttemptValidator(v); err != nil {
			return &ValidationError{Name: "attempt", err: fmt.Errorf(`ent: validator failed for field "WfResult.attempt": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := wfresult.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "WfResult.id": %w`, err)}
		}
	}
	if len(_c.mutation.RunIDs()) == 0 {
		return &ValidationError{Name: "run", err: errors.New(`ent: missing required edge "WfResult.run"`)}
	}
	return nil
}

func (_c *WfResultCreate) sqlSave(ctx context.Context) (*WfResult, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected WfResult.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WfResultCreate) createSpec() (*WfResult, *sqlgraph.CreateSpec) {
	var (
		_node = &WfResult{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(wfresult.Table, sqlgraph.NewFieldSpec(wfresult.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(wfresult.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(wfresult.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(wfresult.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Judge(); ok {
		_spec.SetField(wfresult.FieldJudge, field.TypeString, value)
		_node.Judge = value
	}
	if value, ok := _c.mutation.Outcome(); ok {
		_spec.SetField(wfresult.FieldOutcome, field.TypeString, value)
		_node.Outcome = value
	}
	if value, ok := _c.mutation.Rationale(); ok {
		_spec.SetField(wfresult.FieldRationale, field.TypeString, value)
		_node.Rationale = value
	}
	if value, ok := _c.mutation.Attempt(); ok {
		_spec.SetField(wfresult.FieldAttempt, field.TypeInt, value)
		_node.Attempt = value
	}
	if nodes := _c.mutation.RunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wfresult.RunTable,
			Columns: []string{wfresult.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(run.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RunID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StepIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   wfresult.StepTable,
			Columns: []string{wfresult.StepColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(step.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.StepID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WfResultCreateBulk is the builder for creating many WfResult entities in bulk.
type WfResultCreateBulk struct {
	config
	err      error
	builders []*WfResultCreate
}

// Save creates the WfResult entities in the database.
func (_c *WfResultCreateBulk) Save(ctx context.Context) ([]*WfResult, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WfResult, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WfResultMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WfResultCreateBulk) SaveX(ctx context.Context) []*WfResult {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WfResultCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WfResultCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
