// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/elliot14A/fincher/internal/turso/ent/run"
	"github.com/elliot14A/fincher/internal/turso/ent/step"
	"github.com/elliot14A/fincher/internal/turso/ent/wfresult"
)

// WfResult is the model entity for the WfResult schema.
type WfResult struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RunID holds the value of the "run_id" field.
	RunID string `json:"run_id,omitempty"`
	// StepID holds the value of the "step_id" field.
	StepID string `json:"step_id,omitempty"`
	// Judge holds the value of the "judge" field.
	Judge string `json:"judge,omitempty"`
	// Outcome holds the value of the "outcome" field.
	Outcome string `json:"outcome,omitempty"`
	// Rationale holds the value of the "rationale" field.
	Rationale string `json:"rationale,omitempty"`
	// Attempt holds the value of the "attempt" field.
	Attempt int `json:"attempt,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WfResultQuery when eager-loading is set.
	Edges        WfResultEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WfResultEdges holds the relations/edges for other nodes in the graph.
type WfResultEdges struct {
	// Run holds the value of the run edge.
	Run *Run `json:"run,omitempty"`
	// Step holds the value of the step edge.
	Step *Step `json:"step,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RunOrErr returns the Run value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WfResultEdges) RunOrErr() (*Run, error) {
	if e.Run != nil {
		return e.Run, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: run.Label}
	}
	return nil, &NotLoadedError{edge: "run"}
}

// StepOrErr returns the Step value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WfResultEdges) StepOrErr() (*Step, error) {
	if e.Step != nil {
		return e.Step, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: step.Label}
	}
	return nil, &NotLoadedError{edge: "step"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WfResult) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case wfresult.FieldMetadata:
			values[i] = new([]byte)
		case wfresult.FieldAttempt:
			values[i] = new(sql.NullInt64)
		case wfresult.FieldID, wfresult.FieldRunID, wfresult.FieldStepID, wfresult.FieldJudge, wfresult.FieldOutcome, wfresult.FieldRationale:
			values[i] = new(sql.NullString)
		case wfresult.FieldCreatedAt, wfresult.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WfResult fields.
func (_m *WfResult) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case wfresult.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case wfresult.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case wfresult.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case wfresult.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case wfresult.FieldRunID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field run_id", values[i])
			} else if value.Valid {
				_m.RunID = value.String
			}
		case wfresult.FieldStepID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field step_id", values[i])
			} else if value.Valid {
				_m.StepID = value.String
			}
		case wfresult.FieldJudge:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field judge", values[i])
			} else if value.Valid {
				_m.Judge = value.String
			}
		case wfresult.FieldOutcome:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field outcome", values[i])
			} else if value.Valid {
				_m.Outcome = value.String
			}
		case wfresult.FieldRationale:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rationale", values[i])
			} else if value.Valid {
				_m.Rationale = value.String
			}
		case wfresult.FieldAttempt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt", values[i])
			} else if value.Valid {
				_m.Attempt = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WfResult.
// This includes values selected through modifiers, order, etc.
func (_m *WfResult) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRun queries the "run" edge of the WfResult entity.
func (_m *WfResult) QueryRun() *RunQuery {
	return NewWfResultClient(_m.config).QueryRun(_m)
}

// QueryStep queries the "step" edge of the WfResult entity.
func (_m *WfResult) QueryStep() *StepQuery {
	return NewWfResultClient(_m.config).QueryStep(_m)
}

// Update returns a builder for updating this WfResult.
// Note that you need to call WfResult.Unwrap() before calling this method if this WfResult
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WfResult) Update() *WfResultUpdateOne {
	return NewWfResultClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WfResult entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WfResult) Unwrap() *WfResult {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: WfResult is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WfResult) String() string {
	var builder strings.Builder
	builder.WriteString("WfResult(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("run_id=")
	builder.WriteString(_m.RunID)
	builder.WriteString(", ")
	builder.WriteString("step_id=")
	builder.WriteString(_m.StepID)
	builder.WriteString(", ")
	builder.WriteString("judge=")
	builder.WriteString(_m.Judge)
	builder.WriteString(", ")
	builder.WriteString("outcome=")
	builder.WriteString(_m.Outcome)
	builder.WriteString(", ")
	builder.WriteString("rationale=")
	builder.WriteString(_m.Rationale)
	builder.WriteString(", ")
	builder.WriteString("attempt=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempt))
	builder.WriteByte(')')
	return builder.String()
}

// WfResults is a parsable slice of WfResult.
type WfResults []*WfResult
