import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { FileCode, FileText, Film, type LucideProps, Mic, Plus } from 'lucide-preact'
import type { ComponentType } from 'preact'
import { useEffect, useState } from 'preact/hooks'
import { toast } from 'sonner'
import { Button } from '#/components/ui/button'
import { FormField, SelectInput, TextInput } from '#/components/ui/input'
import { Modal } from '#/components/ui/modal'
import { packagesKeys } from '#/features/packages/queryKeys'
import { titlesQueryOptions } from '#/features/titles/queryOptions'
import { vendorsQueryOptions } from '#/features/vendors/queryOptions'
import { postPackages } from '#/lib/api'
import type { ModelsComponentType, ModelsPackageStatus } from '#/lib/api/generated'
import { slugify } from '#/lib/utils/slugify'
import {
  componentButton,
  componentButtonActive,
  componentToggleGroup,
  form,
  formRow,
} from './modals.css'

export type CreatePackageModalProps = {
  isOpen: boolean
  onClose: () => void
  initialTitleId?: string
}

const COMPONENTS: Array<{
  type: ModelsComponentType
  label: string
  icon: ComponentType<LucideProps>
}> = [
  { type: 'VIDEO', label: 'Video Cut', icon: Film },
  { type: 'AUDIO', label: 'Audio Dub', icon: Mic },
  { type: 'SUBTITLE', label: 'Subtitles', icon: FileText },
  { type: 'METADATA', label: 'Metadata', icon: FileCode },
]

export function CreatePackageModal({ isOpen, onClose, initialTitleId }: CreatePackageModalProps) {
  const queryClient = useQueryClient()

  const { data: titlesData } = useQuery(titlesQueryOptions({ limit: 100 }))
  const { data: vendorsData } = useQuery(vendorsQueryOptions({ limit: 100 }))

  const titleOptions =
    titlesData?.items?.map((t) => ({
      value: t.id,
      label: `${t.name} (${t.id})`,
    })) ?? []

  const vendorOptions =
    vendorsData?.items?.map((v) => ({
      value: v.id,
      label: `${v.name} (${v.specialty})`,
    })) ?? []

  const [titleId, setTitleId] = useState(initialTitleId || '')
  const [vendorId, setVendorId] = useState('')
  const [component, setComponent] = useState<ModelsComponentType>('AUDIO')
  const [language, setLanguage] = useState('de-DE')
  const [version, setVersion] = useState('V01')
  const [derivedMasterVersion, setDerivedMasterVersion] = useState('V01')
  const [status, setStatus] = useState<ModelsPackageStatus>('PENDING')

  useEffect(() => {
    if (initialTitleId) {
      setTitleId(initialTitleId)
    } else if (titleOptions.length > 0 && !titleId) {
      setTitleId(titleOptions[0].value)
    }
  }, [initialTitleId, titleOptions, titleId])

  useEffect(() => {
    if (vendorOptions.length > 0 && !vendorId) {
      setVendorId(vendorOptions[0].value)
    }
  }, [vendorOptions, vendorId])

  const calculatedId =
    titleId && component && language && version
      ? `pkg-${component.toLowerCase()}-${titleId.replace(/^title-/, '')}-${slugify(language)}-${version.toLowerCase()}`
      : ''

  const resetForm = () => {
    if (titleOptions.length > 0) setTitleId(titleOptions[0].value)
    if (vendorOptions.length > 0) setVendorId(vendorOptions[0].value)
    setComponent('AUDIO')
    setLanguage('de-DE')
    setVersion('V01')
    setDerivedMasterVersion('V01')
    setStatus('PENDING')
  }

  const mutation = useMutation({
    mutationFn: async () => {
      if (!titleId) throw new Error('Please select a Title')
      if (!vendorId) throw new Error('Please select a Vendor')
      if (!language.trim()) throw new Error('Language code is required')
      if (!version.trim()) throw new Error('Version is required')

      const { data, error } = await postPackages({
        body: {
          id: calculatedId,
          title_id: titleId,
          vendor_id: vendorId,
          component,
          language: language.trim(),
          version: version.trim(),
          derived_from_master_version: derivedMasterVersion.trim() || 'V01',
          status,
        },
      })

      if (error) {
        throw new Error(error.message || 'Failed to create media package')
      }

      return data
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: packagesKeys.all })
      toast.success(`Package "${data?.id ?? calculatedId}" created successfully`)
      resetForm()
      onClose()
    },
    onError: (err) => {
      toast.error(err instanceof Error ? err.message : 'Failed to create package')
    },
  })

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Create Media Package"
      description="Register a localized or derived component package generated by a post-production vendor."
      footer={
        <>
          <Button variant="ghost" size="sm" onClick={onClose} disabled={mutation.isPending}>
            Cancel
          </Button>
          <Button
            variant="primary"
            size="sm"
            onClick={() => mutation.mutate()}
            disabled={mutation.isPending || !titleId || !vendorId || !language}
          >
            <Plus size={14} />
            <span>{mutation.isPending ? 'Creating...' : 'Create Package'}</span>
          </Button>
        </>
      }
    >
      <form
        class={form}
        onSubmit={(e) => {
          e.preventDefault()
          mutation.mutate()
        }}
      >
        <FormField label="Component Type" required>
          <div class={componentToggleGroup}>
            {COMPONENTS.map((c) => {
              const Icon = c.icon
              const isActive = component === c.type
              return (
                <button
                  type="button"
                  key={c.type}
                  class={isActive ? `${componentButton} ${componentButtonActive}` : componentButton}
                  onClick={() => setComponent(c.type)}
                >
                  <Icon size={18} />
                  <span>{c.label}</span>
                </button>
              )
            })}
          </div>
        </FormField>

        <div class={formRow}>
          <FormField label="Target Title" required>
            <SelectInput
              value={titleId}
              onChange={(e) => setTitleId((e.target as HTMLSelectElement).value)}
              options={
                titleOptions.length > 0
                  ? titleOptions
                  : [{ value: '', label: 'No titles available' }]
              }
            />
          </FormField>

          <FormField label="Producing Vendor" required>
            <SelectInput
              value={vendorId}
              onChange={(e) => setVendorId((e.target as HTMLSelectElement).value)}
              options={
                vendorOptions.length > 0
                  ? vendorOptions
                  : [{ value: '', label: 'No vendors available' }]
              }
            />
          </FormField>
        </div>

        <div class={formRow}>
          <FormField label="Language / Locale" required helper="e.g. en, de-DE, ja-JP">
            <TextInput
              placeholder="de-DE"
              value={language}
              onInput={(e) => setLanguage((e.target as HTMLInputElement).value)}
            />
          </FormField>

          <FormField label="Package Version" required helper="e.g. V01">
            <TextInput
              placeholder="V01"
              value={version}
              onInput={(e) => setVersion((e.target as HTMLInputElement).value)}
            />
          </FormField>
        </div>

        <div class={formRow}>
          <FormField label="Derived Master Cut" required helper="e.g. V01">
            <TextInput
              placeholder="V01"
              value={derivedMasterVersion}
              onInput={(e) => setDerivedMasterVersion((e.target as HTMLInputElement).value)}
            />
          </FormField>

          <FormField label="QC Initial Status" required>
            <SelectInput
              value={status}
              onChange={(e) =>
                setStatus((e.target as HTMLSelectElement).value as ModelsPackageStatus)
              }
              options={[
                { value: 'PENDING', label: 'Pending Inspection' },
                { value: 'VALID', label: 'Valid / QC Passed' },
                { value: 'RE_QC_PENDING', label: 'Re-QC Pending' },
              ]}
            />
          </FormField>
        </div>

        <FormField label="Derived Package ID" helper="System-generated package identifier">
          <TextInput value={calculatedId} disabled />
        </FormField>
      </form>
    </Modal>
  )
}
