// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/elliot14A/fincher/pkg/ent/schema"
	"github.com/elliot14A/fincher/pkg/ent/title"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	titleFields := schema.Title{}.Fields()
	_ = titleFields
	// titleDescName is the schema descriptor for name field.
	titleDescName := titleFields[1].Descriptor()
	// title.NameValidator is a validator for the "name" field. It is called by the builders before save.
	title.NameValidator = titleDescName.Validators[0].(func(string) error)
	// titleDescTerritories is the schema descriptor for territories field.
	titleDescTerritories := titleFields[4].Descriptor()
	// title.DefaultTerritories holds the default value on creation for the territories field.
	title.DefaultTerritories = titleDescTerritories.Default.(int)
	// title.TerritoriesValidator is a validator for the "territories" field. It is called by the builders before save.
	title.TerritoriesValidator = titleDescTerritories.Validators[0].(func(int) error)
	// titleDescCurrentMasterVersion is the schema descriptor for current_master_version field.
	titleDescCurrentMasterVersion := titleFields[5].Descriptor()
	// title.CurrentMasterVersionValidator is a validator for the "current_master_version" field. It is called by the builders before save.
	title.CurrentMasterVersionValidator = titleDescCurrentMasterVersion.Validators[0].(func(string) error)
	// titleDescCreatedAt is the schema descriptor for created_at field.
	titleDescCreatedAt := titleFields[7].Descriptor()
	// title.DefaultCreatedAt holds the default value on creation for the created_at field.
	title.DefaultCreatedAt = titleDescCreatedAt.Default.(func() time.Time)
	// titleDescUpdatedAt is the schema descriptor for updated_at field.
	titleDescUpdatedAt := titleFields[8].Descriptor()
	// title.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	title.DefaultUpdatedAt = titleDescUpdatedAt.Default.(func() time.Time)
	// title.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	title.UpdateDefaultUpdatedAt = titleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// titleDescID is the schema descriptor for id field.
	titleDescID := titleFields[0].Descriptor()
	// title.IDValidator is a validator for the "id" field. It is called by the builders before save.
	title.IDValidator = titleDescID.Validators[0].(func(string) error)
}
