// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/elliot14A/fincher/pkg/ent/master"
	"github.com/elliot14A/fincher/pkg/ent/mediapackage"
	"github.com/elliot14A/fincher/pkg/ent/title"
)

// TitleCreate is the builder for creating a Title entity.
type TitleCreate struct {
	config
	mutation *TitleMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *TitleCreate) SetName(v string) *TitleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetType sets the "type" field.
func (_c *TitleCreate) SetType(v title.Type) *TitleCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *TitleCreate) SetNillableType(v *title.Type) *TitleCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetPremiereDate sets the "premiere_date" field.
func (_c *TitleCreate) SetPremiereDate(v time.Time) *TitleCreate {
	_c.mutation.SetPremiereDate(v)
	return _c
}

// SetTerritories sets the "territories" field.
func (_c *TitleCreate) SetTerritories(v int) *TitleCreate {
	_c.mutation.SetTerritories(v)
	return _c
}

// SetNillableTerritories sets the "territories" field if the given value is not nil.
func (_c *TitleCreate) SetNillableTerritories(v *int) *TitleCreate {
	if v != nil {
		_c.SetTerritories(*v)
	}
	return _c
}

// SetCurrentMasterVersion sets the "current_master_version" field.
func (_c *TitleCreate) SetCurrentMasterVersion(v string) *TitleCreate {
	_c.mutation.SetCurrentMasterVersion(v)
	return _c
}

// SetOverallStatus sets the "overall_status" field.
func (_c *TitleCreate) SetOverallStatus(v title.OverallStatus) *TitleCreate {
	_c.mutation.SetOverallStatus(v)
	return _c
}

// SetNillableOverallStatus sets the "overall_status" field if the given value is not nil.
func (_c *TitleCreate) SetNillableOverallStatus(v *title.OverallStatus) *TitleCreate {
	if v != nil {
		_c.SetOverallStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TitleCreate) SetCreatedAt(v time.Time) *TitleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TitleCreate) SetNillableCreatedAt(v *time.Time) *TitleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TitleCreate) SetUpdatedAt(v time.Time) *TitleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TitleCreate) SetNillableUpdatedAt(v *time.Time) *TitleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TitleCreate) SetID(v string) *TitleCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddMasterIDs adds the "masters" edge to the Master entity by IDs.
func (_c *TitleCreate) AddMasterIDs(ids ...string) *TitleCreate {
	_c.mutation.AddMasterIDs(ids...)
	return _c
}

// AddMasters adds the "masters" edges to the Master entity.
func (_c *TitleCreate) AddMasters(v ...*Master) *TitleCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMasterIDs(ids...)
}

// AddPackageIDs adds the "packages" edge to the MediaPackage entity by IDs.
func (_c *TitleCreate) AddPackageIDs(ids ...string) *TitleCreate {
	_c.mutation.AddPackageIDs(ids...)
	return _c
}

// AddPackages adds the "packages" edges to the MediaPackage entity.
func (_c *TitleCreate) AddPackages(v ...*MediaPackage) *TitleCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPackageIDs(ids...)
}

// Mutation returns the TitleMutation object of the builder.
func (_c *TitleCreate) Mutation() *TitleMutation {
	return _c.mutation
}

// Save creates the Title in the database.
func (_c *TitleCreate) Save(ctx context.Context) (*Title, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TitleCreate) SaveX(ctx context.Context) *Title {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TitleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TitleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TitleCreate) defaults() {
	if _, ok := _c.mutation.GetType(); !ok {
		v := title.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.Territories(); !ok {
		v := title.DefaultTerritories
		_c.mutation.SetTerritories(v)
	}
	if _, ok := _c.mutation.OverallStatus(); !ok {
		v := title.DefaultOverallStatus
		_c.mutation.SetOverallStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := title.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := title.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TitleCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Title.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := title.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Title.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Title.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := title.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Title.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PremiereDate(); !ok {
		return &ValidationError{Name: "premiere_date", err: errors.New(`ent: missing required field "Title.premiere_date"`)}
	}
	if _, ok := _c.mutation.Territories(); !ok {
		return &ValidationError{Name: "territories", err: errors.New(`ent: missing required field "Title.territories"`)}
	}
	if v, ok := _c.mutation.Territories(); ok {
		if err := title.TerritoriesValidator(v); err != nil {
			return &ValidationError{Name: "territories", err: fmt.Errorf(`ent: validator failed for field "Title.territories": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CurrentMasterVersion(); !ok {
		return &ValidationError{Name: "current_master_version", err: errors.New(`ent: missing required field "Title.current_master_version"`)}
	}
	if v, ok := _c.mutation.CurrentMasterVersion(); ok {
		if err := title.CurrentMasterVersionValidator(v); err != nil {
			return &ValidationError{Name: "current_master_version", err: fmt.Errorf(`ent: validator failed for field "Title.current_master_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OverallStatus(); !ok {
		return &ValidationError{Name: "overall_status", err: errors.New(`ent: missing required field "Title.overall_status"`)}
	}
	if v, ok := _c.mutation.OverallStatus(); ok {
		if err := title.OverallStatusValidator(v); err != nil {
			return &ValidationError{Name: "overall_status", err: fmt.Errorf(`ent: validator failed for field "Title.overall_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Title.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Title.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := title.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Title.id": %w`, err)}
		}
	}
	return nil
}

func (_c *TitleCreate) sqlSave(ctx context.Context) (*Title, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Title.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TitleCreate) createSpec() (*Title, *sqlgraph.CreateSpec) {
	var (
		_node = &Title{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(title.Table, sqlgraph.NewFieldSpec(title.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(title.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(title.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.PremiereDate(); ok {
		_spec.SetField(title.FieldPremiereDate, field.TypeTime, value)
		_node.PremiereDate = value
	}
	if value, ok := _c.mutation.Territories(); ok {
		_spec.SetField(title.FieldTerritories, field.TypeInt, value)
		_node.Territories = value
	}
	if value, ok := _c.mutation.CurrentMasterVersion(); ok {
		_spec.SetField(title.FieldCurrentMasterVersion, field.TypeString, value)
		_node.CurrentMasterVersion = value
	}
	if value, ok := _c.mutation.OverallStatus(); ok {
		_spec.SetField(title.FieldOverallStatus, field.TypeEnum, value)
		_node.OverallStatus = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(title.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(title.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.MastersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   title.MastersTable,
			Columns: []string{title.MastersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(master.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PackagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   title.PackagesTable,
			Columns: []string{title.PackagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mediapackage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TitleCreateBulk is the builder for creating many Title entities in bulk.
type TitleCreateBulk struct {
	config
	err      error
	builders []*TitleCreate
}

// Save creates the Title entities in the database.
func (_c *TitleCreateBulk) Save(ctx context.Context) ([]*Title, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Title, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TitleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TitleCreateBulk) SaveX(ctx context.Context) []*Title {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TitleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TitleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
