// Code generated by ent, DO NOT EDIT.

package delivery

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the delivery type in the database.
	Label = "delivery"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitleID holds the string denoting the title_id field in the database.
	FieldTitleID = "title_id"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTargetDate holds the string denoting the target_date field in the database.
	FieldTargetDate = "target_date"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTitle holds the string denoting the title edge name in mutations.
	EdgeTitle = "title"
	// Table holds the table name of the delivery in the database.
	Table = "deliveries"
	// TitleTable is the table that holds the title relation/edge.
	TitleTable = "deliveries"
	// TitleInverseTable is the table name for the Title entity.
	// It exists in this package in order to avoid circular dependency with the "title" package.
	TitleInverseTable = "titles"
	// TitleColumn is the table column denoting the title relation/edge.
	TitleColumn = "title_id"
)

// Columns holds all SQL columns for delivery fields.
var Columns = []string{
	FieldID,
	FieldTitleID,
	FieldCountry,
	FieldStatus,
	FieldTargetDate,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleIDValidator is a validator for the "title_id" field. It is called by the builders before save.
	TitleIDValidator func(string) error
	// CountryValidator is a validator for the "country" field. It is called by the builders before save.
	CountryValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPENDING is the default value of the Status enum.
const DefaultStatus = StatusPENDING

// Status values.
const (
	StatusPENDING       Status = "PENDING"
	StatusREADY_TO_SHIP Status = "READY_TO_SHIP"
	StatusHOLD          Status = "HOLD"
	StatusSHIPPED       Status = "SHIPPED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPENDING, StatusREADY_TO_SHIP, StatusHOLD, StatusSHIPPED:
		return nil
	default:
		return fmt.Errorf("delivery: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Delivery queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitleID orders the results by the title_id field.
func ByTitleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitleID, opts...).ToFunc()
}

// ByCountry orders the results by the country field.
func ByCountry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountry, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTargetDate orders the results by the target_date field.
func ByTargetDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetDate, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTitleField orders the results by title field.
func ByTitleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTitleStep(), sql.OrderByField(field, opts...))
	}
}
func newTitleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TitleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TitleTable, TitleColumn),
	)
}
