// Code generated by ent, DO NOT EDIT.

package delivery

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/elliot14A/fincher/internal/turso/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Delivery {
	return predicate.Delivery(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Delivery {
	return predicate.Delivery(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Delivery {
	return predicate.Delivery(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Delivery {
	return predicate.Delivery(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Delivery {
	return predicate.Delivery(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Delivery {
	return predicate.Delivery(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Delivery {
	return predicate.Delivery(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Delivery {
	return predicate.Delivery(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Delivery {
	return predicate.Delivery(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Delivery {
	return predicate.Delivery(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Delivery {
	return predicate.Delivery(sql.FieldContainsFold(FieldID, id))
}

// TitleID applies equality check predicate on the "title_id" field. It's identical to TitleIDEQ.
func TitleID(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldEQ(FieldTitleID, v))
}

// Country applies equality check predicate on the "country" field. It's identical to CountryEQ.
func Country(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldEQ(FieldCountry, v))
}

// TargetDate applies equality check predicate on the "target_date" field. It's identical to TargetDateEQ.
func TargetDate(v time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldEQ(FieldTargetDate, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldEQ(FieldUpdatedAt, v))
}

// TitleIDEQ applies the EQ predicate on the "title_id" field.
func TitleIDEQ(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldEQ(FieldTitleID, v))
}

// TitleIDNEQ applies the NEQ predicate on the "title_id" field.
func TitleIDNEQ(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldNEQ(FieldTitleID, v))
}

// TitleIDIn applies the In predicate on the "title_id" field.
func TitleIDIn(vs ...string) predicate.Delivery {
	return predicate.Delivery(sql.FieldIn(FieldTitleID, vs...))
}

// TitleIDNotIn applies the NotIn predicate on the "title_id" field.
func TitleIDNotIn(vs ...string) predicate.Delivery {
	return predicate.Delivery(sql.FieldNotIn(FieldTitleID, vs...))
}

// TitleIDGT applies the GT predicate on the "title_id" field.
func TitleIDGT(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldGT(FieldTitleID, v))
}

// TitleIDGTE applies the GTE predicate on the "title_id" field.
func TitleIDGTE(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldGTE(FieldTitleID, v))
}

// TitleIDLT applies the LT predicate on the "title_id" field.
func TitleIDLT(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldLT(FieldTitleID, v))
}

// TitleIDLTE applies the LTE predicate on the "title_id" field.
func TitleIDLTE(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldLTE(FieldTitleID, v))
}

// TitleIDContains applies the Contains predicate on the "title_id" field.
func TitleIDContains(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldContains(FieldTitleID, v))
}

// TitleIDHasPrefix applies the HasPrefix predicate on the "title_id" field.
func TitleIDHasPrefix(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldHasPrefix(FieldTitleID, v))
}

// TitleIDHasSuffix applies the HasSuffix predicate on the "title_id" field.
func TitleIDHasSuffix(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldHasSuffix(FieldTitleID, v))
}

// TitleIDEqualFold applies the EqualFold predicate on the "title_id" field.
func TitleIDEqualFold(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldEqualFold(FieldTitleID, v))
}

// TitleIDContainsFold applies the ContainsFold predicate on the "title_id" field.
func TitleIDContainsFold(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldContainsFold(FieldTitleID, v))
}

// CountryEQ applies the EQ predicate on the "country" field.
func CountryEQ(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldEQ(FieldCountry, v))
}

// CountryNEQ applies the NEQ predicate on the "country" field.
func CountryNEQ(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldNEQ(FieldCountry, v))
}

// CountryIn applies the In predicate on the "country" field.
func CountryIn(vs ...string) predicate.Delivery {
	return predicate.Delivery(sql.FieldIn(FieldCountry, vs...))
}

// CountryNotIn applies the NotIn predicate on the "country" field.
func CountryNotIn(vs ...string) predicate.Delivery {
	return predicate.Delivery(sql.FieldNotIn(FieldCountry, vs...))
}

// CountryGT applies the GT predicate on the "country" field.
func CountryGT(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldGT(FieldCountry, v))
}

// CountryGTE applies the GTE predicate on the "country" field.
func CountryGTE(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldGTE(FieldCountry, v))
}

// CountryLT applies the LT predicate on the "country" field.
func CountryLT(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldLT(FieldCountry, v))
}

// CountryLTE applies the LTE predicate on the "country" field.
func CountryLTE(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldLTE(FieldCountry, v))
}

// CountryContains applies the Contains predicate on the "country" field.
func CountryContains(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldContains(FieldCountry, v))
}

// CountryHasPrefix applies the HasPrefix predicate on the "country" field.
func CountryHasPrefix(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldHasPrefix(FieldCountry, v))
}

// CountryHasSuffix applies the HasSuffix predicate on the "country" field.
func CountryHasSuffix(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldHasSuffix(FieldCountry, v))
}

// CountryEqualFold applies the EqualFold predicate on the "country" field.
func CountryEqualFold(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldEqualFold(FieldCountry, v))
}

// CountryContainsFold applies the ContainsFold predicate on the "country" field.
func CountryContainsFold(v string) predicate.Delivery {
	return predicate.Delivery(sql.FieldContainsFold(FieldCountry, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Delivery {
	return predicate.Delivery(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Delivery {
	return predicate.Delivery(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Delivery {
	return predicate.Delivery(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Delivery {
	return predicate.Delivery(sql.FieldNotIn(FieldStatus, vs...))
}

// TargetDateEQ applies the EQ predicate on the "target_date" field.
func TargetDateEQ(v time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldEQ(FieldTargetDate, v))
}

// TargetDateNEQ applies the NEQ predicate on the "target_date" field.
func TargetDateNEQ(v time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldNEQ(FieldTargetDate, v))
}

// TargetDateIn applies the In predicate on the "target_date" field.
func TargetDateIn(vs ...time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldIn(FieldTargetDate, vs...))
}

// TargetDateNotIn applies the NotIn predicate on the "target_date" field.
func TargetDateNotIn(vs ...time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldNotIn(FieldTargetDate, vs...))
}

// TargetDateGT applies the GT predicate on the "target_date" field.
func TargetDateGT(v time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldGT(FieldTargetDate, v))
}

// TargetDateGTE applies the GTE predicate on the "target_date" field.
func TargetDateGTE(v time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldGTE(FieldTargetDate, v))
}

// TargetDateLT applies the LT predicate on the "target_date" field.
func TargetDateLT(v time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldLT(FieldTargetDate, v))
}

// TargetDateLTE applies the LTE predicate on the "target_date" field.
func TargetDateLTE(v time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldLTE(FieldTargetDate, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Delivery {
	return predicate.Delivery(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasTitle applies the HasEdge predicate on the "title" edge.
func HasTitle() predicate.Delivery {
	return predicate.Delivery(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TitleTable, TitleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTitleWith applies the HasEdge predicate on the "title" edge with a given conditions (other predicates).
func HasTitleWith(preds ...predicate.Title) predicate.Delivery {
	return predicate.Delivery(func(s *sql.Selector) {
		step := newTitleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Delivery) predicate.Delivery {
	return predicate.Delivery(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Delivery) predicate.Delivery {
	return predicate.Delivery(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Delivery) predicate.Delivery {
	return predicate.Delivery(sql.NotPredicates(p))
}
