// Code generated by ent, DO NOT EDIT.

package master

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/elliot14A/fincher/pkg/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Master {
	return predicate.Master(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Master {
	return predicate.Master(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Master {
	return predicate.Master(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Master {
	return predicate.Master(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Master {
	return predicate.Master(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Master {
	return predicate.Master(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Master {
	return predicate.Master(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Master {
	return predicate.Master(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Master {
	return predicate.Master(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Master {
	return predicate.Master(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Master {
	return predicate.Master(sql.FieldContainsFold(FieldID, id))
}

// TitleID applies equality check predicate on the "title_id" field. It's identical to TitleIDEQ.
func TitleID(v string) predicate.Master {
	return predicate.Master(sql.FieldEQ(FieldTitleID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.Master {
	return predicate.Master(sql.FieldEQ(FieldVersion, v))
}

// SupersedesVersion applies equality check predicate on the "supersedes_version" field. It's identical to SupersedesVersionEQ.
func SupersedesVersion(v string) predicate.Master {
	return predicate.Master(sql.FieldEQ(FieldSupersedesVersion, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Master {
	return predicate.Master(sql.FieldEQ(FieldCreatedAt, v))
}

// TitleIDEQ applies the EQ predicate on the "title_id" field.
func TitleIDEQ(v string) predicate.Master {
	return predicate.Master(sql.FieldEQ(FieldTitleID, v))
}

// TitleIDNEQ applies the NEQ predicate on the "title_id" field.
func TitleIDNEQ(v string) predicate.Master {
	return predicate.Master(sql.FieldNEQ(FieldTitleID, v))
}

// TitleIDIn applies the In predicate on the "title_id" field.
func TitleIDIn(vs ...string) predicate.Master {
	return predicate.Master(sql.FieldIn(FieldTitleID, vs...))
}

// TitleIDNotIn applies the NotIn predicate on the "title_id" field.
func TitleIDNotIn(vs ...string) predicate.Master {
	return predicate.Master(sql.FieldNotIn(FieldTitleID, vs...))
}

// TitleIDGT applies the GT predicate on the "title_id" field.
func TitleIDGT(v string) predicate.Master {
	return predicate.Master(sql.FieldGT(FieldTitleID, v))
}

// TitleIDGTE applies the GTE predicate on the "title_id" field.
func TitleIDGTE(v string) predicate.Master {
	return predicate.Master(sql.FieldGTE(FieldTitleID, v))
}

// TitleIDLT applies the LT predicate on the "title_id" field.
func TitleIDLT(v string) predicate.Master {
	return predicate.Master(sql.FieldLT(FieldTitleID, v))
}

// TitleIDLTE applies the LTE predicate on the "title_id" field.
func TitleIDLTE(v string) predicate.Master {
	return predicate.Master(sql.FieldLTE(FieldTitleID, v))
}

// TitleIDContains applies the Contains predicate on the "title_id" field.
func TitleIDContains(v string) predicate.Master {
	return predicate.Master(sql.FieldContains(FieldTitleID, v))
}

// TitleIDHasPrefix applies the HasPrefix predicate on the "title_id" field.
func TitleIDHasPrefix(v string) predicate.Master {
	return predicate.Master(sql.FieldHasPrefix(FieldTitleID, v))
}

// TitleIDHasSuffix applies the HasSuffix predicate on the "title_id" field.
func TitleIDHasSuffix(v string) predicate.Master {
	return predicate.Master(sql.FieldHasSuffix(FieldTitleID, v))
}

// TitleIDEqualFold applies the EqualFold predicate on the "title_id" field.
func TitleIDEqualFold(v string) predicate.Master {
	return predicate.Master(sql.FieldEqualFold(FieldTitleID, v))
}

// TitleIDContainsFold applies the ContainsFold predicate on the "title_id" field.
func TitleIDContainsFold(v string) predicate.Master {
	return predicate.Master(sql.FieldContainsFold(FieldTitleID, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.Master {
	return predicate.Master(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.Master {
	return predicate.Master(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.Master {
	return predicate.Master(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.Master {
	return predicate.Master(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.Master {
	return predicate.Master(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.Master {
	return predicate.Master(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.Master {
	return predicate.Master(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.Master {
	return predicate.Master(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.Master {
	return predicate.Master(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.Master {
	return predicate.Master(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.Master {
	return predicate.Master(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.Master {
	return predicate.Master(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.Master {
	return predicate.Master(sql.FieldContainsFold(FieldVersion, v))
}

// SupersedesVersionEQ applies the EQ predicate on the "supersedes_version" field.
func SupersedesVersionEQ(v string) predicate.Master {
	return predicate.Master(sql.FieldEQ(FieldSupersedesVersion, v))
}

// SupersedesVersionNEQ applies the NEQ predicate on the "supersedes_version" field.
func SupersedesVersionNEQ(v string) predicate.Master {
	return predicate.Master(sql.FieldNEQ(FieldSupersedesVersion, v))
}

// SupersedesVersionIn applies the In predicate on the "supersedes_version" field.
func SupersedesVersionIn(vs ...string) predicate.Master {
	return predicate.Master(sql.FieldIn(FieldSupersedesVersion, vs...))
}

// SupersedesVersionNotIn applies the NotIn predicate on the "supersedes_version" field.
func SupersedesVersionNotIn(vs ...string) predicate.Master {
	return predicate.Master(sql.FieldNotIn(FieldSupersedesVersion, vs...))
}

// SupersedesVersionGT applies the GT predicate on the "supersedes_version" field.
func SupersedesVersionGT(v string) predicate.Master {
	return predicate.Master(sql.FieldGT(FieldSupersedesVersion, v))
}

// SupersedesVersionGTE applies the GTE predicate on the "supersedes_version" field.
func SupersedesVersionGTE(v string) predicate.Master {
	return predicate.Master(sql.FieldGTE(FieldSupersedesVersion, v))
}

// SupersedesVersionLT applies the LT predicate on the "supersedes_version" field.
func SupersedesVersionLT(v string) predicate.Master {
	return predicate.Master(sql.FieldLT(FieldSupersedesVersion, v))
}

// SupersedesVersionLTE applies the LTE predicate on the "supersedes_version" field.
func SupersedesVersionLTE(v string) predicate.Master {
	return predicate.Master(sql.FieldLTE(FieldSupersedesVersion, v))
}

// SupersedesVersionContains applies the Contains predicate on the "supersedes_version" field.
func SupersedesVersionContains(v string) predicate.Master {
	return predicate.Master(sql.FieldContains(FieldSupersedesVersion, v))
}

// SupersedesVersionHasPrefix applies the HasPrefix predicate on the "supersedes_version" field.
func SupersedesVersionHasPrefix(v string) predicate.Master {
	return predicate.Master(sql.FieldHasPrefix(FieldSupersedesVersion, v))
}

// SupersedesVersionHasSuffix applies the HasSuffix predicate on the "supersedes_version" field.
func SupersedesVersionHasSuffix(v string) predicate.Master {
	return predicate.Master(sql.FieldHasSuffix(FieldSupersedesVersion, v))
}

// SupersedesVersionIsNil applies the IsNil predicate on the "supersedes_version" field.
func SupersedesVersionIsNil() predicate.Master {
	return predicate.Master(sql.FieldIsNull(FieldSupersedesVersion))
}

// SupersedesVersionNotNil applies the NotNil predicate on the "supersedes_version" field.
func SupersedesVersionNotNil() predicate.Master {
	return predicate.Master(sql.FieldNotNull(FieldSupersedesVersion))
}

// SupersedesVersionEqualFold applies the EqualFold predicate on the "supersedes_version" field.
func SupersedesVersionEqualFold(v string) predicate.Master {
	return predicate.Master(sql.FieldEqualFold(FieldSupersedesVersion, v))
}

// SupersedesVersionContainsFold applies the ContainsFold predicate on the "supersedes_version" field.
func SupersedesVersionContainsFold(v string) predicate.Master {
	return predicate.Master(sql.FieldContainsFold(FieldSupersedesVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Master {
	return predicate.Master(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Master {
	return predicate.Master(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Master {
	return predicate.Master(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Master {
	return predicate.Master(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Master {
	return predicate.Master(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Master {
	return predicate.Master(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Master {
	return predicate.Master(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Master {
	return predicate.Master(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTitle applies the HasEdge predicate on the "title" edge.
func HasTitle() predicate.Master {
	return predicate.Master(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TitleTable, TitleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTitleWith applies the HasEdge predicate on the "title" edge with a given conditions (other predicates).
func HasTitleWith(preds ...predicate.Title) predicate.Master {
	return predicate.Master(func(s *sql.Selector) {
		step := newTitleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Master) predicate.Master {
	return predicate.Master(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Master) predicate.Master {
	return predicate.Master(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Master) predicate.Master {
	return predicate.Master(sql.NotPredicates(p))
}
